### ISSUE TITLE
Reorganize core.js?

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basil.js#106]
While trying to lint core.js I ran into a problem that can be solved by changing some function definitions.  

I would love to change:  

    var setCurrDoc = function(doc){}

to:

    function setCurrDoc (){}

In a stricter environment the first wouldn't even work. `setCurrDoc` would be marked as `undefined`. I just want a GO on this before I start reorganizing the core.js

**Comment by b-g** [comment]
Hi @fabianmoronzirfas, feel free to change those "js accidents"! Sorry for the mess! For most of us incl. myself, basil was the first big javascript project back 4-5 years ago ... So we simply were simply sometimes overwhelmed by the flexibility and expressiveness of javascript. Best, B
