### ISSUE TITLE
itemWidth() and itemHeight() don't work for pages

### ISSUE THREAD

**Issue by b-g** [basiljs/basil.js#11]
please refactor it with obj.reframe(new bounds) ... then it would be more general e.g. work for pages

**Comment by fabiantheblind** [comment]
Should this be a feature or should we close this?

**Comment by b-g** [comment]
now that we are touching everything: feature

**Comment by fabiantheblind** [comment]
Great. Don't feel urged to response immediately. I'm just going through the issues to  separate bugs, features, requests, user problems and sort them by milestone to have an overview.

**Comment by trych** [comment]
itemWidth and itemHeight don't exist anymore. I suggest that the `bounds()` function will be able to measure pages in the future. Opening a new issue for this and closing this one.
