### ISSUE TITLE
b.words(doc), b.lines(doc) etc. are broken

### ISSUE THREAD

**Issue by trych** [basiljs/basil.js#116]
(Last class there was a lot of stuff coming up that was broken/not working as expected, so I will have to add a few issues again)

`b.words()`, `b.lines()` etc. are not working when using `doc` as the container, although the documentation suggest they should. The (now broken) sample script [`forEach-loops.jsx`](https://github.com/basiljs/basil.js/blob/master/scripts/examples/structure/forEach-loops.jsx) suggests that it did work in the past.

The actual issue is [in this line](https://github.com/basiljs/basil.js/blob/master/src/includes/structure.js#L53), where it checks for the property `content`, which a document does not have. 

And while we're at it fixing this, I suggest we also allow `page` as a possible container.

**Comment by fabianmoronzirfas** [comment]
@trych I think this is solved. Isn't it? Closing for now

**Comment by trych** [comment]
Yes, it's solved, thanks for closing.
