### ISSUE TITLE
b.clear() is slow and throws confusing warnings

### ISSUE THREAD

**Issue by trych** [basiljs/basil.js#117]
The use of `pub.forEach()` in `b.clear()` makes it incredibly slow. Clearing 200 circles or so regularly takes a few seconds.

Also, `b.clear()` throws confusing warnings when images are cleared (because it uses the container's `allPageItems` which also counts all graphics and then when the graphic's frame is cleared first,`b.clear()` throws the warning `forEach(), invalid object processed.`)

I therefore suggest to rather clear items like this:
```js
container.pageItems.everyItem().remove();
```

This would be *much* faster. The only problem is that we'll have to unlock all items first, so locked items will be cleared as well. But I doubt that it really happens that someone wants to clear a collection but then keep locked items in this collection. (And if they really do, they could instead move these items to another layer first).

**Comment by fabianmoronzirfas** [comment]
Will locked items throw an error or just don't get cleared?

**Comment by trych** [comment]
It does throw an error, that's why we have to unlock them all first. So it would be

```js
container.pageItems.everyItem().locked = false;
container.pageItems.everyItem().remove();
```

**Comment by b-g** [comment]
👍 faster! Unlocking shouldn't be a problem!

**Comment by trych** [comment]
Side question: If I create some benchmark basil script(s) to test the fix, would it be okay to just add these to the `test/benchmarks` folder? Or do you prefer that I do not add them to the repo?

**Comment by b-g** [comment]
IMO sure! +1
@fabianmoronzirfas plz veto if this sabotages any master plan.

**Comment by fabianmoronzirfas** [comment]
Sure. I don't know what it could break to have some benchmarking scripts :-)
