### ISSUE TITLE
b.itemScale()

### ISSUE THREAD

**Issue by trych** [basiljs/basil.js#121]
Introduce `b.itemScale()` to conveniently scale an item by a scale factor.

`b.itemScale(item, 2)` -> scales the item by factor 2 in both dimensions.

`b.itemScale(item, 2, 3)` -> scales the item by different factors in both dimensions

`b.itemScale(item, 1, 4)` -> scales only the height of the image by factor 4

**Comment by fabianmoronzirfas** [comment]
In Processing there is the `scale()` method https://processing.org/reference/scale_.html Should we now:  

- Keep working the processing way? (So everything from then on should be scaled)
- Do the object approach and pass objects to things.

I think this is a decision that should be made on a "global" level not only for this particular example

**Comment by trych** [comment]
> I think this is a decision that should be made on a "global" level not only for this particular example 

Well, I think this decision has already been made by the basil team by introducing the whole class of `b.itemXXX()` commands. In basil we already do have `b.scale()`, too, so in that regard it is compatible with Processing, we just have this whole extra set of `b.itemXXX()` commands additionally, which I find is very useful.

And I think `b.itemScale()` could be a good addition to that.

**Comment by fabianmoronzirfas** [comment]
Seems like you already thought a lot about it. 😊 I still think there is room for confusion with the proposed itemSize and the already existing scale

**Comment by trych** [comment]
> the proposed itemSize

`b.itemSize()` does exist already. In #122 I'm just suggesting to make it more versatile.

As it stands we already have

```
b.itemHeight()
b.itemWidth()
b.itemPosition()
b.itemSize()
b.itemX()
b.itemY()
```

and I am only suggesting here to add `b.itemScale()` to that.

This way we don't have to do

```js
var img = b.image("img.jpg", 0, 0);
var w = b.itemWidth(img);
var h = b.itemHeight(img);
b.itemSize(img, w * 3, h * 3);
```

but could simply do

```js
var img = b.image("img.jpg", 0, 0);
b.itemScale(img, 3);
```

instead.

**Comment by b-g** [comment]
Hi all, sorry for the slow responses but Tue/Wed are my hardcore uni days ...

> RE: I think this is a decision that should be made on a "global" level not only for this particular example 

Many thanks for all the thoughts and energy behind. I would go down a totally different route, as I think introducing so many new functions would yield little gain. What about making use of js-style object with props as input parameter? That way we simply had two functions and not a zillion small ones ...

```
b.transformImage({propName:value})
b.transformItem({propName:value})
```

RE: b.itemScale() vs. b.itemSize()
Also here not super fond of introducing even more functions, why not b.itemSize()?
`b.itemSize(3, SCALE)`

@ffd8 what do you think?

**Comment by trych** [comment]
> as I think introducing so many new functions would yield little gain

Again, the functions

```js
b.itemHeight()
b.itemWidth()
b.itemPosition()
b.itemSize()
b.itemX()
b.itemY()
```

do already exist. 😄 This is merely about adding an additional `b.itemScale()`. IMHO I think `b.itemSize(item, 3, SCALE)` is not less confusing than introducing one more function.

**Comment by ffd8** [comment]
Great ideas here– but also agree that this would be one of many possible transformations that could/should be combined into more 'swiss-army-knife' (??) functions. We have b.typo() – what would the the equivalent names for dealing with other types of objects? @b-g I find the wording 'transformItem()' + 'transformImage()' long, especially when comparing to the short and sweet b.typo() « I think I have a crush on that function... so also wondering if item/image need to be split. Most likely yes- since they are such different types with own possibilities.. but how should we deal with it? b.text is to b.typo, as b.image is to b.???

Started to write out proposals for wording.. but will do so on the #43 since that discussion deals more broadly with changes.

**Comment by trych** [comment]
This can be closed, as the scale functionality will be included in the new `transform()` method and the `itemX` functions are obsolete now.
