### ISSUE TITLE
b.itemSize() with single size argument

### ISSUE THREAD

**Issue by trych** [basiljs/basil.js#122]
Additionally to the previously suggested transformation improvements, it would also be nice if `b.itemSize()` could also just take a single argument for the size and automatically calculate the other dimension.

Example with a `var rect = b.rect(0, 0, 100, 200)`:

`b.itemSize(rect, 200)` -> resizes the rect to 200, 400.

`b.itemSize(rect, undefined, 300)` -> resizes the rect to 150, 300.

**Comment by fabianmoronzirfas** [comment]
I find this confusing. So the function should assume that I want a proportional scale if I leave out the second parameter? It is pretty close to the proposed #121 itemScale()

**Comment by trych** [comment]
> It is pretty close to the proposed #121 itemScale()

Yes, but it's not the same. It is helpful in cases, where I want to say: Ok, I need this image with an height of exactly 37 mm.

**Comment by fabianmoronzirfas** [comment]
What would be the way to just scale the width and leaving the height untouched?

**Comment by trych** [comment]
Hm. Damn, good point. That would need to be `b.itemSize(rect, 300, undefined)` for consistency and that brings me to a point, where I myself find this whole suggestion to confusing. 😜 Thanks for looking into this, though, sometimes you need a second opinion to realize something is stupid. 😉

Closing this.

**Comment by fabianmoronzirfas** [comment]
I think we should concentrate the effort on this issue/feature #43 setting and getting properties.
