### ISSUE TITLE
b.SCRIPT_NAME

### ISSUE THREAD

**Issue by trych** [basiljs/basil.js#123]
Introduce a constant `b.SCRIPT_NAME` that contains the name of the current script as a string.

This could be used for the following things:

1. To give a more precise message in InDesign's Undo-Command (that's where the idea originally came from). So the Menu would not state `Undo: Script` but rather `Undo: helloWorld.jsx` which is nice and useful if several scripts are execute in sequence.

2. For the basil.js log message in the console.

3. For the potentially upcoming [`b.log()`](https://github.com/basiljs/basil.js/issues/50).

4. For users to use it for whatever.

**Comment by fabianmoronzirfas** [comment]
I'd suggest `b.SCRIPTNAME` (without underscore). But I think this needs to be a function of some kind. So `b.scriptname()` ?

    b.SCRIPTNAME = File($.fileName).exists === true ? File($.fileName).name : ($.writeln('error message'));

This gives me the error message. Which is great but if we populate b.scriptname from Basil.js which is included I think we will get "Basil.js" as result. Not the user script.

**Comment by b-g** [comment]
+1 for `b.SCRIPTNAME` (without underscore)!
But should we not get rid of the file extension `(new File($.fileName)).name.slice(0, -4)`, so you can use `b.SCRIPTNAME` to e.g. name things without fiddling around ...

**Comment by fabianmoronzirfas** [comment]
> But should we not get rid of the file extension   

Good point.  

BTW: You don't need to use the `new` to get a `File` that already exists.

**Comment by fabianmoronzirfas** [comment]
Is the slice(0, -4) bullet proofed against `.js` or even files without extension? I think we should use some kind of regex for this  like this example http://stackoverflow.com/a/4250408/1770432

**Comment by trych** [comment]
Yes, leaving out the extension is a good idea and using a regex for handling both `.jsx` and `.js` also.

Btw., there is also `app.activeScript` for "The current script running from the Scripts panel." Is this what we need or `$.fileName`?

**Comment by fabianmoronzirfas** [comment]
Well we should try it out. I always us the `$.fileName` but only because it works on all applications. (e.g. AE, AI etc)

**Comment by b-g** [comment]
to summarize the conversation:
 
decision: b.SCRIPTNAME 
decision: use a regex to be on the safe side
decision: for `$.fileName` as `app.activeScript` is not working is you execute a script from outside e.g. via Sublime.

**Comment by trych** [comment]
This just got merged. Closing.
