### ISSUE TITLE
Why is forEach made global?

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basil.js#125]
In [src/includes/global-functions.js Line 81](https://github.com/basiljs/basil.js/blob/master/src/includes/global-functions.js#L81) we are making forEach globally available. Why is that so? Everything else is just a child of pub/b (actuall HashList this is also global)  

Any idea why this is that way?

**Comment by b-g** [comment]
Yes, this was done a long time ago on purpose to "extend" extendscript even further "didactical" . To my knowledge nobody every used `forEach`. I would not mind to remove this ...

I guess HashList would be with the new b.less concept global anyway.

@ffd8 ok?

**Comment by fabianmoronzirfas** [comment]
> I guess HashList would be with the new b.less concept global anyway.

HashList is only global and not in the pub/b scope. I'll check the source if `forEach` is somewhere used as global. If so I'll change this to the b scope version. The problem (why i noticed that) is that having this in global and b scope creates an edge case for checking if the user created functions and variables that overwrite the Basil ones. See https://github.com/basiljs/basil.js/blob/b-less/src/includes/core.js#L48

**Comment by trych** [comment]
@b-g Are you suggesting to make forEach non-global or to remove it altogether?

**Comment by fabianmoronzirfas** [comment]
> Are you suggesting to make forEach non-global or to remove it altogether?

I think it is used somewhere. With the b-less version it will be global again but in another place with all the other basil functions.

**Comment by trych** [comment]
Yes, that sounds good.

**Comment by b-g** [comment]
Question seems answered. closed.
