### ISSUE TITLE
Assigning issues

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basil.js#130]
We should start assigning issues to have responsibilities. There is a lot of un assigned issues around:  

https://github.com/basiljs/basil.js/issues?utf8=%E2%9C%93&q=is%3Aissue%20no%3Aassignee%20

**Comment by trych** [comment]
Ok, I assigned myself to a lot of issues now, mainly the ones that I reported. If I took anybody's darling, let me know. I cannot make any promises at how fast I can tackle them, but I'm on it.

**Comment by fabianmoronzirfas** [comment]
Same goes for me I assigned myself to some issues. If there are still some oben no biggy but it is good that one person keeps track of an issue and closes or updates it accordingly.
