### ISSUE TITLE
Docs as gh-pages

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basil.js#131]
For the time being (as long as the Basil site is not updated) we should build the docs into gh-pages might be also useful for moving the whole site in the future so maintainers can update right away.  

Problem is it does not support PHP. So there needs to be an entire rebuild

**Comment by fabianmoronzirfas** [comment]
This might be a possibility to add a search to the docs http://lunrjs.com/

**Comment by b-g** [comment]
Would http://documentation.js.org/ be the tool of choice to replace the old documentation building workflow?

**Comment by fabianmoronzirfas** [comment]
@b-g yeah maybe. I tried it some long time ago and it didn't work well. If it is stable I will try it out. (I also think we should walk away from yuidoc)

**Comment by b-g** [comment]
@fabianmoronzirfas Ok + I think it is stable as Mapbox is using it for the documentation ...

**Comment by trych** [comment]
This has been implemented by @fabianmoronzirfas. All further issues concerning the documentation or its implementation should go in the dedicated repo.
