### ISSUE TITLE
extend b.inspect

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basil.js#142]
inspect is buggy and should be extended.

```js
function prop (f) {
  $.writeln (f.reflect.name);
  var props = f.reflect.properties;
  var array = [];
  for (var i = 0; i < props.length; i++)
  try {array.push (props[i].name + ": " + f[props[i].name])} catch (_){} array.sort ();
  $.writeln (array.join ("\r"));
}

function meth (m) {
  var props = m.reflect.methods.sort(); $.writeln ("\rMethods");
  for (var i = 0; i < props.length; i++)
  $.writeln (props[i].name);
}
```

Taken from Peter Kahrels ScriptUI Handbook http://www.kahrel.plus.com/indesign/scriptui.html

**Comment by trych** [comment]
How should we implement this?

Maybe have a second optional argument, which can receive the constants `b.PROPERTIES` for properties only and `b.METHODS` for methods only? And you call it without second argument, it would give you property/value pairs as it currently does?

**Comment by b-g** [comment]
Not very keen on more constants, maybe rather?

```js
b.inspect({properties:true, methods:false})
```

**Comment by fabianmoronzirfas** [comment]
or even:  

    b.inspect(obj,true /* props */, false /* meths */);

???

**Comment by fabianmoronzirfas** [comment]
missing arguments should default to `true`

**Comment by trych** [comment]
Ok, coming back to this, as this is one of the things I would like to tackle next (we could really use it in our projects at the moment).

I think we should have the following options with `b.inspect()`, that would all move into the settings object:
* show/hide properties
* show/hide values (can only be shown when properties are shown)
* show/hide methods
* maxlevels

What should be the defaults for those? I'm not sure they should all default to true.
How about
* show properties
* show values
* hide methods
* maxlevels: 1 (for performance reasons; if people realize that's too little, they can always increase it)

Thoughts? Something missing?

**Comment by fabianmoronzirfas** [comment]
I would go for:  all true and maxlevels 1.

**Comment by trych** [comment]
This has been done via #190.
