### ISSUE TITLE
b.isNumber() returns true for strings

### ISSUE THREAD

**Issue by trych** [basiljs/basil.js#143]
Statements like

```js
b.isNumber("3");
```
return true, which should not be the case. Or is `b.isNumber()` also supposed to figure out if a string is a "number string"?

**Comment by fabianmoronzirfas** [comment]
Looks like by design

https://github.com/basiljs/basil.js/blob/403bd59fe964cf83b07206b947022ad02c7c1e00/src/includes/data.js#L678

**Comment by trych** [comment]
Yeah, I saw the code, but still I think `isNumber()` strongly suggests that the function checks, if the type of the argument equals JavaScript's Number type. Should it not be changed to work that way?

Was just using it to check if `b.CSV.decode` returns number fields as numbers or strings and `b.number()` gave me some debugging headache as I assumed it would work the other way.

**Comment by b-g** [comment]
This is bug. Sorry! Let's blame [Stackoverflow](http://stackoverflow.com/questions/9716468/is-there-any-function-like-isnumeric-in-javascript-to-validate-numbers) :)

**Comment by b-g** [comment]
fixed. sorry mixed up branches. no PR, just a single commit.
