### ISSUE TITLE
Expand basil.js to work with Files and Folders

### ISSUE THREAD

**Issue by trych** [basiljs/basil.js#144]
As discussed [in our Skype call](https://github.com/basiljs/basil.js/wiki/Basil.js-Team-Call-Summary#production-tool) recently, basil.js should offer some ways to work with files and folders. After giving this some thought, I suggest the following implementation (which is rather straightforward):

- `b.file()`
  - `b.file(filepath)` returns the file; if the file does not exist, returns `false`.
  - `b.file()` opens the Open File dialog (= ExtendScript's `File.openDialog()`)
- `b.folder()`
  - `b.folder(folderpath)` returns the folder; if the folder does not exist, returns `false`.
  - `b.folder()` opens the Select Folder dialog (= ExtendScript's `Folder.selectDialog()`)
- `b.getFiles()`
  - `b.getFiles(folder)` returns files of a folder as an array
  - `b.getFiles(folder, "png")` returns all .png files of a folder

This way we could check for a files existence, return a file and select a file via dialog all in the same function, which would make it quite useful.

Any thoughts?

**Comment by fabianmoronzirfas** [comment]
IMO `file` and `folder` should create that file/folder if does not exist.

**Comment by b-g** [comment]
There are related functions around in the processing mothership and p5js:
https://processing.org/reference/selectInput_.html
https://processing.org/reference/selectFolder_.html
https://p5js.org/reference/#/p5/createFileInput

Hence I would rather propose ...

Open File dialog (= ExtendScript's `File.openDialog()`) ... filepath = optinal, would be handy to set sometimes the folder of the dialog
- `b.fileInput(filepath)` 
- `b.folderInput(filepath)`

`b.file(filepath)` returns the file; if the file does not exist, returns `false`.
`b.file({filepath:filepath, create:true})`

`b.folder(folderpath)` returns the folder; if the folder does not exist, returns `false`.
`b.folder({filepath:filepath, create:true})`

`b.files(folder)` returns files of a folder as an array
`b.files({filepath:filepath, filemask:'.png', showhidden:false})` returns all .png files of a folder

Also what about having all the time a cb function?

**Comment by trych** [comment]
> b.folderInput(filepath)

IMO `b.selectFolder(filepath)` would be more descriptive of what's about to happen.

> b.file({filepath:filepath, create:true})

I have to say I am not a big fan of the `{key: value, key: value}` notation in this context. We do not use it anywhere else as the only argument and I think if it is just about setting `create` to `true` we might as well just allow a second optional argument that would be false be default (if not set).

The `b.files()` as you proposed it could also do completely without a `{key: value, key: value}` notation, like `b.files(folderPath, [filemask], [showhidden])`, although I would skip showhidden altogether. If a user starts to deal with hidden files, he should be able to figure out how to address these files without a basil wrapper. I have never needed to read a hidden file via ExtendScript so far. 😉

**Comment by b-g** [comment]
@trych OK what about:
```
b.selectFolder
b.selectFile
b.file
b.folder

b.files
// or referencing 
// https://github.com/isaacs/node-glob
// https://docs.python.org/3/library/glob.html
// http://www.computerhope.com/dirhlp.htm
b.glob
b.dir
```
I like the `{key: value}` notation better as it is more descriptive e.g. what was again the 3 parameter in this function ... but I can also live with the old school way if the others and you find it better.

**Comment by fabianmoronzirfas** [comment]
> I like the {key: value} notation better as it is more descriptive

Me too, but this should be applied throughout Basil. Also for teaching it would mean to teach the key value concept at the beginning. Makes it harder I think. It also adds more possibilities for typos

**Comment by trych** [comment]
> I like the {key: value} notation better as it is more descriptive e.g. what was again the 3 parameter in this function ...

I think the main thing bothering me with your `b.files({filepath:filepath, filemask:'.png', showhidden:false})` suggestion is that `filepath: filepath` is part of the the options object, although it is a parameter that is required anyways.

I think, if we do `b.files(filepath, {filemask:'.png', showhidden:false}) instead it is cleaner, as the parameter that is always required is there outside the settings object and just the parameters that are options are in that object. Which is also how stuff like `b.characterStyle(name, {props})` is implemented now.

So, if you guys are fine with it, I would suggest this notation

`b.files(filepath, {filemask:'.png', showhidden:false})`

that leaves the required parameters as their own argument and moves all the optional paremeters into an settings object. And if you agree, I also think we should introduce this to other functions of basil and in the process get rid of some of the b.CONSTANTS that are used at the moment.

**Comment by b-g** [comment]
@trych convinced! :) 👍

```js
b.files(filepath)
b.files(filepath, {filemask:'.png', showhidden:false}) // with optional args
```

**Comment by ffd8** [comment]
Also a fan of making it easy 'one param' files getter + options.

Just to throw in some aspects to consider.. 
- drop the '.' on a mask.. just ask for the suffix
- option for multiple, case-insensative, filters (space or comma separated)? (png,  jpg, JPEG, tiff)
- recursive folder searching option?

**Comment by trych** [comment]
Like all three of these suggestions. This way the file functions get really useful and more than just a wrapper. Cool! 👍

**Comment by fabianmoronzirfas** [comment]
Just a heads up. I remembered that file filtering was bit wired on macOS compared to Win. On macOS you need to pass a function as filter mask. On Win it is a array of glob patterns. See these links for further infos.  

http://stackoverflow.com/questions/25492829/allow-all-file-types-to-be-selected-in-extendscripts-file-object-opendlg-meth

https://forums.adobe.com/thread/2053260

https://forums.adobe.com/thread/470603

**Comment by b-g** [comment]
Yes naming looks! ... We could also use an array for a filemask with multiples endings:
```js
b.files(filepath, {filemask:'png'})
b.files(filepath, {filemask:['png','PNG']})
```

**Comment by trych** [comment]
Ok, to summarize the discussion (as I want to work on this soon):

There will be 5 new methods:

`b.selectFile()`: Opens a file selection dialog, returns the selected file.
`b.selectFolder()`: Opens a folder selection dialog, returns the selected folder.

`b.file()`: Returns a file.
`b.folder()`: Returns a folder.

`b.files()`: Returns files of a specific folder.

And now that I have given this some thought, I think there should also be

`b.selectFiles()`: Opens a file selection dialog to select multiple files.

**Comment by trych** [comment]
> IMO file and folder should create that file/folder if does not exist.

@fabianmoronzirfas I agree, they should be created in the ExtendScript DOM (not on the hard drive). So, you could do something like:

```js
var exportFile = b.file("~/Desktop/myNewFile.pdf");
b.savePDF(exportFile);
```
Is that what you mean?

**Comment by fabianmoronzirfas** [comment]
Well. Following up a discussion from 2016 :-) Hard to remember what I was thinking then. I think it depends on the situation. We can't create a pdf on the fly, but text files. We can create folders on the fly. Not sure what happens with deep nested paths. We will need to test this.

**Comment by fabianmoronzirfas** [comment]
cool.  
```js
var folder = Folder('~/Desktop/foo/bah/baz');
if(!folder.exists){
       folder.create();
    }
```

Creates the whole tree

**Comment by trych** [comment]
Yes, since we can't create all file types on the fly, I would _not_ create files on the hard drive, else it would get super confusing. And then since we don't do that, I would also not create folders on the hard drive via `b.folder()`. Just create them in the DOM instead.

Also, I just realized, creating folders on the hard drive could be potentially very inconvenient. Let's say the user does have a typo/mistake in his folder path (which happens all the time when trying to get a path syntax just right). Then he just keeps creating incorrect folders and at the same time does not get any error feedback and does not now that he is not targeting the folder he intended to target.

Instead, if you want to create new folders, you can just do:

```js
```js
var exportFile = b.file("~/Desktop/myNewFolder/myNewFile.pdf");
b.savePDF(exportFile);  // new folder gets created with new file in it
```

**Comment by fabianmoronzirfas** [comment]
What do you mean by   

>  Just create them in the DOM instead.

???

**Comment by trych** [comment]
I mean to just create an file object by doing

```js
  var myNewFile = new File("~/Desktop/myNewFile.txt");
  $.writeln(myNewFile.constructor.name);  // --> File
  $.writeln(myNewFile.exists);  // --> false
```

instead of creating an actual file on the disc. The creation of actual files should be connected to our save commands `b.savePDF()` etc.

**Comment by trych** [comment]
Ok, first question:

What do we do with statements like

```js
var myRandomFile = b.file("someRandomFolder/someRandomFile.pdf");
b.savePDF(myRandomFile);
```
where the given path is _not_ in the user folder and `someRandomFolder` does not exist yet.
Apparently InDesign cannot create folders outside the user folder (which is probably a good thing) … Should we allow `b.file()` to only work within the user folder? Or should we also allow it to create files in folders that already exist outside the user folder (which is possible) and otherwise throw an error?

**Comment by trych** [comment]
This has been merged into the `develop` branch a while ago.

**Comment by ffd8** [comment]
@trych – these functions are so great, really making life easy for bringing in many photos for laying out! One small improvement it could use (not exactly sure how best to implement = why I bring it up here), when asking for a recursive files within a folder, a method to keep the structure for the folder each file was found in. Essentially, a tree like so:

```
- main_dir
	- dir_1
		- img_1
		- img_2
		- img_3
		- txt
	- dir_2
		- img_1
		- img_2
		- txt
```

Right now, one would select the folder, use `files` with recursive on, then get a big array of the files.. but if one wants to set a new page per directory or then do another filter for txt documents so that it automatically embeds one txt per the images it found in that dir.. wondering how best to do that. I'm wondering if it's best to build an extended function from `folder` and have a `folders` – which returns an array of all dirs inside of it.. OR allow the `files` function to have a filter flag for just returning dirs, which could then be looped through.. or return a recursive list of files as a 2D array, like `[dir][filename]`?
