### ISSUE TITLE
Are we moving to properties objects?

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basil.js#146]
Just a question:  Are we moving to properties objects? Like mentioned in #142 #144 
If so: Will we refactor existing functions for v2.x?  

I like the idea of having a properties object, but would vote for having it consistent throughout the library.

**Comment by b-g** [comment]
@fabianmoronzirfas good question. I'm ok to have both mixed. I see it rather as a way to have "expert" parameters (most of the time optional) in a nicer way.

No, anti pattern!
```js
b.rect({x:10, y:10, width:45, height:50});
```

Yes!
```js
b.inspect(obj) // should work out of the box with the defaults
b.inspect(obj, {properties:true, methods:false}) // with expert options
```

What are the others thinking?

**Comment by ffd8** [comment]
I agree that such functions should work on a very basic basic level of just function(obj) – then allow the optional fancy {name:value, ...} pair settings if extending.

**Comment by trych** [comment]
I agree as well, just would like to add that I would only have this "expert options" object as long as there are _several_ properties to set, not just one.

So

```js
b.inspect(obj, {properties:true, methods:false})
```
is fine, while

```js
b.someFunction(obj, {onlyPropertyToSet: true});`
```

should not be allowed, but should use a constant or a boolean instead.
