### ISSUE TITLE
Sublime Text 3 Mac - can't run scripts

### ISSUE THREAD

**Issue by blank-tree** [basiljs/basil.js#147]
I receive an error message, when I try to build a basil.js script with Sublime Text 3
I get the following error message:
`osascript: /Users/MY_USERNAME/Library/Application Support/Sublime Text 3/Packages/Basiljs/run_idscript_CC_2017.scpt: No such file or directory`

I also can't find this directory in the terminal, because the spaces are not correctly used. I think it should be:
`/Users/fo/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Basiljs`

but I don't know where to change this behaviour. The folders are all there, and the same script works in InDesign with the Adobe ExtendScript Toolkit

**Comment by blank-tree** [comment]
Found the issue:
In the README for the sublime text extra is an error
[https://github.com/basiljs/basil.js/tree/master/extras/Sublime%20Text](https://github.com/basiljs/basil.js/tree/master/extras/Sublime%20Text)
It should be
`~/Library/Application Support/Sublime Text 3/Packages/Basiljs`
not
`~/Library/Application Support/Sublime Text 3/Packages/**User/**Basiljs`

**Comment by trych** [comment]
I can really recommend using [RunInIndesign](https://github.com/vamitul/RunInIndesign). Easy install via PackageManager and it offers also console output in Sublime. I teach basil.js and my entire course uses it.
