### ISSUE TITLE
install.bat paths not correct (windows)

### ISSUE THREAD

**Issue by andreirt** [basiljs/basil.js#156]
Dear BasilJS team,

at color.jsx, for example, we have:

```js
#includepath "~/Documents/;%USERPROFILE%Documents";
#include "basiljs/bundle/basil.js";
```

To this work at Windows, I had to

1. add a slash before Documents
```js
#includepath "~/Documents/;%USERPROFILE%/Documents";
```

2. change install.bat from 

```js
md   %userprofile%\Documents\basiljs-target
xcopy . %userprofile%\Documents\basiljs-target\bundle\ /E
md %userprofile%\Documents\basiljs-target\user
```

to

```js
md   %userprofile%\Documents\basiljs
xcopy . %userprofile%\Documents\basiljs\bundle\ /E
md %userprofile%\Documents\basiljs\user
```

I am thinking about changing this and submitting a pull request. Does this seem ok for you?

Best,
Andrei

**Comment by trych** [comment]
Hi Andrei, thanks for reporting an issue.
The paths in the install.bat seem definitely wrong, they should not point to basiljs-target.

About the slash before Documents I am not sure. I have some students in my basil.js course using windows that did not have any problems using the current

```js
#includepath "~/Documents/;%USERPROFILE%Documents";
```

Could you double check if the problems are not resolved simply by changing `basiljs-target` to `basiljs` (_without_ changing the include path)? Unfortunately we cannot really test this easily, as we are all working on OS X.

**Comment by fabianmoronzirfas** [comment]
@andreirt Which Windows version are you on and on which ID version are you working?  

I will setup a testing environment for Windows in a VM next year.

**Comment by andreirt** [comment]
@trych indeed, after changing the path basiljs-target to basiljs at install.bat, all the scripts worked, without changing the include path.

@fabianmoronzirfas I am using Windows 10. By ID version do you mean BasilJS version or CC version? The CC version is the last one, and the BasilJS version is the one can be downloaded at BasilJS website., 1.0.10.

**Comment by trych** [comment]
@andreirt Cool, then this seems to be the only problem. Feel free to do a pull request to fix this.

You will need to do the pull request against the `develop` branch, not the `master` branch. The install.bat script will most likely be expanded in the near future as we are in the process of changing the folder structure of basil.js, but it won't hurt to fix the incorrect paths right now.

**Comment by andreirt** [comment]
I downloaded the fix today, it worked ;-)
