### ISSUE TITLE
Review JSDoc comments @b-g

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basil.js#173]
- [x] environment.js
- [x] global-functions.js
- [x] image.js
- [x] math.js

**Comment by fabianmoronzirfas** [comment]
👍  🚀

**Comment by b-g** [comment]
Reopened, todo: check for "Optional, parameter desc"

**Comment by b-g** [comment]
Closed again with https://github.com/basiljs/basil.js/pull/187
