### ISSUE TITLE
Review JSDoc comments @trych

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basil.js#174]
- [ ] private-vars.js
- [ ] public-vars.js
- [ ] shape.js
- [ ] main.js

**Comment by fabianmoronzirfas** [comment]
In line 181 https://github.com/basiljs/basil.js/blob/develop/src/includes/shape.js#L181
the mode param is not in `[]` brackets. So it is not tagged as optional. But the descriptions says so… 🤓

**Comment by fabianmoronzirfas** [comment]
The line 164 needs the `@description` tag https://github.com/basiljs/basil.js/blob/develop/src/includes/shape.js#L164 The HTML in there will not be rendered.  https://github.com/basiljs/basil.js/wiki/Writing-Documentation#descriptions

**Comment by trych** [comment]
Fabian, thanks, I will not get around to look into this before March 6th again. But then I should be able to go over it.

**Comment by fabianmoronzirfas** [comment]
No problemo. I just looked over the output yesterday night and saw these errors. Just wanted to write them down. Nu hurry.

**Comment by trych** [comment]
Was fixed in #186.
