### ISSUE TITLE
Transform all todos in the source code into github issues.

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basil.js#193]

**Comment by fabianmoronzirfas** [comment]
I extracted all the todos…
[src/includes/data.js](https://github.com/basiljs/basil.js/blob/develop/src/includes/data.js)

|Line Number| Comment|
|:--|:--|
|[443:](https://github.com/basiljs/basil.js/blob/develop/src/includes/data.js#L443)| /* todo */|
|[448:](https://github.com/basiljs/basil.js/blob/develop/src/includes/data.js#L448)| /* todo */|
|[966:](https://github.com/basiljs/basil.js/blob/develop/src/includes/data.js#L966)| // TODO: make savePDF and savePNG D.R.Y.|

[src/includes/global-functions.js](https://github.com/basiljs/basil.js/blob/develop/src/includes/global-functions.js)  

|Line Number| Comment|
|:--|:--|
|[109:](https://github.com/basiljs/basil.js/blob/develop/src/includes/global-functions.js#L109)|   // TODO: initial function removal in items?|

[src/includes/environment.js](https://github.com/basiljs/basil.js/blob/develop/src/includes/environment.js)

|Line Number| Comment|
|:--|:--|
|[236:](https://github.com/basiljs/basil.js/blob/develop/src/includes/environment.js#L236)|     var p = pub.page(page); // get the page object, todo: add an internal method of page retrieval without setting it to current|

[src/includes/math.js](https://github.com/basiljs/basil.js/blob/develop/src/includes/math.js) 

|Line Number| Comment|
|:--|:--|
|[959:](https://github.com/basiljs/basil.js/blob/develop/src/includes/math.js#L959)|     // TODO: not sure if this 100% correct, check|
|[960:](https://github.com/basiljs/basil.js/blob/develop/src/includes/math.js#L960)|      // http://en.wikipedia.org/wiki/File:Typography_Line_Terms.svg|

[src/includes/shape.js](https://github.com/basiljs/basil.js/blob/develop/src/includes/shape.js)  

|Line Number| Comment|
|:--|:--|
|[080:](https://github.com/basiljs/basil.js/blob/develop/src/includes/shape.js#L080)|  *  TODO: Vectors as arguments|
|[182:](https://github.com/basiljs/basil.js/blob/develop/src/includes/shape.js#L182)|  * @todo fix overlapping points bug|

[src/includes/transformation.js](https://github.com/basiljs/basil.js/blob/develop/src/includes/transformation.js)  

|Line Number| Comment|
|:--|:--|
|[150:](https://github.com/basiljs/basil.js/blob/develop/src/includes/transformation.js#L150)|  * @todo Add more description.|
|[173:](https://github.com/basiljs/basil.js/blob/develop/src/includes/transformation.js#L173)|    * @todo More description.|
|[191:](https://github.com/basiljs/basil.js/blob/develop/src/includes/transformation.js#L191)|  * @todo More description.|
|[213:](https://github.com/basiljs/basil.js/blob/develop/src/includes/transformation.js#L213)|    * @todo More description.|
|[225:](https://github.com/basiljs/basil.js/blob/develop/src/includes/transformation.js#L225)|    * @todo More description.|
|[247:](https://github.com/basiljs/basil.js/blob/develop/src/includes/transformation.js#L247)|    * @todo More description.|
|[260:](https://github.com/basiljs/basil.js/blob/develop/src/includes/transformation.js#L260)|    * @todo More description.|
|[272:](https://github.com/basiljs/basil.js/blob/develop/src/includes/transformation.js#L272)|    * @todo More description.|
|[280:](https://github.com/basiljs/basil.js/blob/develop/src/includes/transformation.js#L280)|    * @todo More description.|
|[315:](https://github.com/basiljs/basil.js/blob/develop/src/includes/transformation.js#L315)|    * @todo More description.|
|[328:](https://github.com/basiljs/basil.js/blob/develop/src/includes/transformation.js#L328)|    * @todo More description.|
|[349:](https://github.com/basiljs/basil.js/blob/develop/src/includes/transformation.js#L349)|    * @todo More description.|
|[360:](https://github.com/basiljs/basil.js/blob/develop/src/includes/transformation.js#L360)|    * @todo More description.|
|[387:](https://github.com/basiljs/basil.js/blob/develop/src/includes/transformation.js#L387)|    * @todo More description.|
|[407:](https://github.com/basiljs/basil.js/blob/develop/src/includes/transformation.js#L407)|    * @todo More description.|
|[422:](https://github.com/basiljs/basil.js/blob/develop/src/includes/transformation.js#L422)|    * @todo More description.|
|[447:](https://github.com/basiljs/basil.js/blob/develop/src/includes/transformation.js#L447)|    * @todo More description.|
|[472:](https://github.com/basiljs/basil.js/blob/develop/src/includes/transformation.js#L472)|    * @todo More description.|
|[492:](https://github.com/basiljs/basil.js/blob/develop/src/includes/transformation.js#L492)|    * @todo More description.|
|[503:](https://github.com/basiljs/basil.js/blob/develop/src/includes/transformation.js#L503)|    * @todo More description.|
|[514:](https://github.com/basiljs/basil.js/blob/develop/src/includes/transformation.js#L514)|    * @todo More description.|
|[641:](https://github.com/basiljs/basil.js/blob/develop/src/includes/transformation.js#L641)|  * @todo  Can we make the argument comparison typesafe? != vs !==|

**Comment by b-g** [comment]
Many thanks for this!

To be honest, I would not too much bother with it. Basically just remove everything and close this single big legacy @TODO github issue for documentation. We didn't have the time to deal with it for years ... and there are more pressing things than old forgotten legacy todos. The ratio of effort and outcome feels just very bad for me.

Or?

**Comment by fabianmoronzirfas** [comment]
Its fine with me. Only thing I think what is worth taking a look at is the documentation for the Matrix2D class. There seems to be no documentation for it. But this is also something for an evening with a nice bottle of wine/beer/water and nothing better to do. 😄

**Comment by b-g** [comment]
Ok + I couldn't find any documentation on the Matrix2D back then ... was a total deadend.

**Comment by trych** [comment]
This can be closed, I think?

**Comment by fabianmoronzirfas** [comment]
yes
