### ISSUE TITLE
Checking for `currPage` and `currDoc` fails in certain situaions.

### ISSUE THREAD

**Issue by trych** [basiljs/basil.js#203]
As I'm trying to implement `b.revert()`(#133) , I ran into a bug.

Background: If you have saved the current page in a variable `currPage` and *then* revert the doc, the variable will still hold a page object, but at the same time it returns that this page object equals null.

You can test this small script to check for yourself:

```js
// @target InDesign

var doc = app.activeDocument;
var currPage = doc.layoutWindows[0].activePage;

// add something, so the document can be reverted
currPage.ovals.add();

doc.revert();

$.writeln("currPage: " + currPage);  // [objectPage]
$.writeln("currPage instanceof Page: " + (currPage instanceof Page));  // true
$.writeln("currPage === null: " + (currPage === null));  // true (!)
```

This makes the checks for [currPage](https://github.com/basiljs/basil.js/blob/f34b8a3722dd635dc0dd7cc45edfc595865e1f58/basil.js#L1039) and the [currDoc](https://github.com/basiljs/basil.js/blob/f34b8a3722dd635dc0dd7cc45edfc595865e1f58/basil.js#L912) fail, as they do not enter the `if(!currPage)` if clause and after that mess up pretty badly (as basil.js) continues while thinking it holds a valid page object.

I therefore propose that the checks will be changed to

```
if(currPage === null)
```

or, to be on the safe side

```
if(currPage === null || !currPage)
```
(although I don't think that it ever receives anything else apart from `null` or `[object Page]`.

This post serves more as a reference for the person that will review my `b.revert()` PR once it's done, to explain why I changed these checks. 😉

**Comment by fabianmoronzirfas** [comment]
Okay. So we can close this one. The changes are in #204
