### ISSUE TITLE
Example Script Bundle / Repo

### ISSUE THREAD

**Issue by trych** [basiljs/basil.js#206]
Hi,
my new class starts tomorrow and I am thinking about how to best organize stuff. I realized it might be best to move all example scripts to a specific place where it is easy for people to download them and where we can be sure that they stay in the same place. I.e. a place where we always find the most up to date example script folder.

What would be the easiest / most appropriate way to do this? Should we always zip the examples to one file? Or should we create a dedicated repo for this, something like `https://github.com/basiljs/example-scripts/`.

Or is there a better way?

What do you think?

**Comment by fabianmoronzirfas** [comment]
I am +1 on moving them out of the core repo. "basiljs/examples" is enough for the repo name INHO

**Comment by b-g** [comment]
+1 Good call! Either a separate repo `https://github.com/basiljs/examples` or everything simply in the code repo `https://github.com/basiljs/basil.js/examples`. I think the first one is cleaner, but will create some complexity in regards of bundling the official download packages.

In any case it would be great to do in the near future a 2.0 release of all the current achievements, doesn't make sense for me to wait another year. I would vote for a "this is what we got" 2.0 release end of Feb 2018.

**Comment by fabianmoronzirfas** [comment]
> I think the first one is cleaner, but will create some complexity in regards of bundling the official download packages.  

But not impossible. You can pull in git repos with npm and then have some build script to copy everything into a folder and zip it. Can also be done with gulp or similar task runners.   

> In any case it would be great to do in the near future a 2.0 release of all the current achievements, doesn't make sense for me to wait another year. I would vote for a "this is what we got" 2.0 release end of Feb 2018.

Sounds great. I hope I get soon some time to work on the docs again. 😄  ⏲  (a rare good).  

Another thing about 2.0 I don't think that it is possible to remove the good old `b.` without putting everything in the global scope. This would also mean a huge refactor of the lib.

**Comment by trych** [comment]
Ok, great. I will move them all to `https://github.com/basiljs/examples` then.

> In any case it would be great to do in the near future a 2.0 release of all the current achievements, doesn't make sense for me to wait another year. I would vote for a "this is what we got" 2.0 release end of Feb 2018.

I would agree to make a release finally at some point, but there is a few things that I would say should definitively be implemented before we do this. One of them would be to get rid of `b.` unless …

> I don't think that it is possible to remove the good old b. without putting everything in the global scope. This would also mean a huge refactor of the lib.

Noooooooo. 😱 How did you come to this conclusion? Have you tried out some things?

Anyways, there is 2 or three other things that I think should be included in basil.js 2.0. I think for quicker agreeing on targets and plans another Skype call would be good. What do you guys think? Should we try to schedule a Skype call via private email?

**Comment by fabianmoronzirfas** [comment]
> Noooooooo. 😱 How did you come to this conclusion? Have you tried out some things?

 Of course I did. The big problem is to get the `go`  executed. If I move everything into the global scope it works.

**Comment by b-g** [comment]
+1 for a Skype call in the next weeks. Just not in the next 2 weeks (semester starts + on a crazy deadline for the new edition of Generative Gestaltung) ... let's aim for mid/end of Oct.

**Comment by trych** [comment]
![bildschirmfoto 2017-09-28 um 21 03 20](https://user-images.githubusercontent.com/9803905/30985505-a5a7ccfe-a490-11e7-889a-f3545a3bd088.png)

Insufficient permissions to create a new repo. 😢
Can someone either create a new one named examples for me (with empty README.md and MIT license) or give me permission to create one myself? Thanks! 😉

**Comment by trych** [comment]
> The big problem is to get the go executed. If I move everything into the global scope it works.

I just checked, what we decided in the last meeting and the decision was to try to get rid of `b.go()`, [see here](https://github.com/basiljs/basil.js/wiki/Basil.js-Team-Call-Summary#bgo-draw-and-setup). (And also to replace `function draw` by `function setup`).

Also, in [this discussion](https://github.com/basiljs/basil.js/issues/38) here it does not sound like you guys were opposing making it global. Anyways, I am absolutely not the expert in this stuff and I think it is probably easiest to discuss this in the next Skype meeting. :)

**Comment by fabianmoronzirfas** [comment]
Don't have the permission either…

**Comment by b-g** [comment]
Done! Here we go: https://github.com/basiljs/examples

Team skype: will send a doodle with dates ...

**Comment by trych** [comment]
This is done, all further issues concerning the examples should be opened in the dedicated repo.
