### ISSUE TITLE
b.download + /data folder

### ISSUE THREAD

**Issue by ffd8** [basiljs/basil.js#21]
the b.download function rocks! but i just ran into one issue. similar to the style of b.saveStrings - it is by default downloading the file in the same folder as the indesign file.. however once you want to use the image with b.image - it's by default searching for the /data dir - if you don't save the image with /data - then you'll never find it = shouldn't that be the base location? if someone wants to get more organized and sort images into special folders like "trees/tree_01.jpg" for the path, then the end path is actually "data/trees/tree_01.jpg" - and they can grab the image by using b.image("trees/tree_01.jpg", 0, 0);

Otherwise, awesome work and time to create a book from EVERY google image...

**Comment by fabiantheblind** [comment]
closed by ad594c6
