### ISSUE TITLE
b.startsWith and b.endsWith give cryptic error on passing objects

### ISSUE THREAD

**Issue by trych** [basiljs/basil.js#213]
When `b.startsWith()` or `b.endsWith()` are used with a (word, paragraph, etc. ...) object instead of a string it gives the cryptic error message:

```js
ReferenceError: str.indexOf is not a function
```
There should be a more meaningful error message, as this error happens all the time.

**Comment by fabianmoronzirfas** [comment]
Yes it should. I think it is the overall try catch that produces that.

**Comment by trych** [comment]
Yes, we just need to check the inputs for actually being strings.
Btw., I also used this as an in-class demo how to write issues on GitHub. ;)

**Comment by fabianmoronzirfas** [comment]
> Btw., I also used this as an in-class demo how to write issues on GitHub. ;)
double + good!

**Comment by trych** [comment]
Fixed in #215 .
