### ISSUE TITLE
b.println() should allow multiple parameters

### ISSUE THREAD

**Issue by trych** [basiljs/basil.js#216]
`b.println()` should allow for more than one parameter. At the moment, it just prints the first parameter to console.

Also, and this is a question, not a suggestion: p5.js replaced `println()` by just `print()` (and therefore removed a dedicated `print()` method). Processing still has both. Would it make any sense to replace the `b.println()` command by `b.print()` for easier typing?

**Comment by b-g** [comment]
At the moment I would vote to have both ... to have maximum compatibility with p5 and processing.

**Comment by fabianmoronzirfas** [comment]
Me to. Also `print` should be equivalent to `$.write` wit no new line

**Comment by trych** [comment]
Ok. Not sure, if I've ever seen someone use `b.print()`, but no harm in leaving the methods as they are.

Then we should just allow for multiple parameters.

**Comment by ffd8** [comment]
Also vote for definitely keeping b.println() – b.print() doesn't hurt to have a version that doesn't auto add the new line.. but also never use it myself, since println is soo useful!

**Comment by fabianmoronzirfas** [comment]
+1 on the multiple parameters. :-)

**Comment by trych** [comment]
Implemented via #235.
Closing.
