### ISSUE TITLE
Any way to rotate objects about a center point?

### ISSUE THREAD

**Issue by trych** [basiljs/basil.js#220]
Hi there,
was yesterday asked by a student how to achieve something like this:

![bildschirmfoto 2017-11-22 um 10 19 55](https://user-images.githubusercontent.com/9803905/33119275-b78ee336-cf6e-11e7-81d0-2076cc2d3bbd.png)

While I thought this was super easy, it turned out to be quite impossible. In p5.js it simply would work with this code:

```js
function setup() {
  createCanvas(200, 200);
  background(255, 0, 0);
  translate(width / 2, height / 2);
  
  for(var i = 0; i < 8; i++) {
    ellipse(50, 0, 20, 20);
    rotate( radians(45) );
  }

}
```

However, I could find no appropriate way to do the same in basil. `b.rotate()` only rotates an object around its center (and not around the current reference point), so that cannot be used.

Then I looked into `b.Matrix2D` and `b.Matrix2D.rotate()` but could not get it to work at all. Does somebody have an example of how they are supposed to be used?

And more importantly, how do we rotate something around a center point? I ended up giving her a solution to group the dot with an invisible line first to be able to achieve such a rotation, but that surely cannot be the best solution. Any ideas?

**Comment by fabianmoronzirfas** [comment]
I would do it like that. https://gist.github.com/fabianmoronzirfas/a8743a9663e95cb606f8

**Comment by fabianmoronzirfas** [comment]
I think I once asked for some code comments and Bene told me that the matrix stuff needs some love. There might be an issue about that

**Comment by trych** [comment]
> I would do it like that. https://gist.github.com/fabianmoronzirfas/a8743a9663e95cb606f8

Now, if only I would be smart enough to work with `sin` and `cos` beyond copying and pasting. 😭

I guess I can get this snippet to work. But I think we seriously need a way to rotate the matrix in basil.js. When we get the item transform that could replace the current item rotation `b.rotate()`, but then `b.rotate()` should be really changed to behave like it does in Processing and p5.js.

@b-g @ffd8 Do you maybe have a working sample of using `b.Matrix2D` or `b.Matrix2D.rotate()`, so I could check if this could be used in this case?

**Comment by b-g** [comment]
This was unfortunately never resolved, as the Matrix stuff was over my head and everybody else involved. The problem is, that the Matrix definition of processing and indesign are not the same. I don't think there is a way to fix it, unless paying somebody really math savvy to do it.

But a rotatePoint() would not be a big deal ... basically the core formula for this is:

```
var newX = centerX + cos(radians(angle))*radius;
var newY = centerY + sin(radians(angle))*radius;
```

**Comment by trych** [comment]
@b-g Hm, alright. But what about the `b.Matrix2D` stuff, was that working at some point? I mean, else it would not have been included I guess. Do you remember who implemented it and could give some hint, how it is supposed to be used?

**Comment by fabianmoronzirfas** [comment]
I tried to follow it in the commit history somewhere in 2013 there was a big refactor. It also went from PMatrix2D to Matrix2D and then I got lost… :-)

**Comment by fabianmoronzirfas** [comment]
Maybe we should try to implement a solution that makes use of the indesign functions and not use the Processing.js code as base. I still would put this in a backlog. We could even remove the Matrix stuff for now from the codebase and put this feature into a backlog.

**Comment by b-g** [comment]
Well it is currently a mix of both and that is also the problem. Basically PMatrix2D or Matrix2D is a one to one copy and paste from the old processing.js source. The only thing I've added was [adobeMatrix()](https://github.com/basiljs/basil.js/blob/master/src/includes/transformation.js#L159) so that you could use the processing translate syntax and ["apply"](adobeMatrix) it to an indesign object. Unfortunately the both matrix definitions are not 100% identical and just work as expected for basic translation and scale related operations as expected. I repeat no one in the old team was hard core math enough to figure it out. The only was to fix this is IMO to hire a real math person. I can't help, I've tried back then for days! :(

**Comment by trych** [comment]
No worries, I think I'm the least math savvy person around here. ;)

But @b-g, does that mean the `b.Matrix2D` is basically unusable and we can take it out?

**Comment by fabianmoronzirfas** [comment]
I mean we create a issue for that and stash it :-)

**Comment by b-g** [comment]
Before we take it out ... my math savvy colleague Hartmut @bohnacker will have a quick look over the xmas break and assess the difficulty of it. If Hartmut reports back a 👎 we take it out, otherwise hopefully can fix it. I will brief Hartmut before xmas with the details of the issue.

**Comment by trych** [comment]
Cool, is he familiar with the specifics of the ExtendScript matrix? If not, we could gather some links for him (I'm thinking Marc Autret articles etc.).

**Comment by b-g** [comment]
No, but Hartmut is besides many things also very good with math in a very creative way. And please, some carefully curated explanation documentation links are for sure helpful. Please post in new issue. Cheers.

**Comment by trych** [comment]
> Please post in new issue.

Ok, done: #222.
@b-g: I tried to explain the basic issue in (probably way too) simple terms. The two linked documents by Marc Autret probably give the best overview over Adobe matrices, as he describes them in great detail (which the Adobe docs fail to do). Please edit my post, if something is wrong or missing.

Will close this issue.

**Comment by b-g** [comment]
@trych Thanks!
