### ISSUE TITLE
Processing Foundation 2018 Fellowship Application

### ISSUE THREAD

**Issue by b-g** [basiljs/basil.js#225]
FYI ... could be something for basil.js ... @trych @fabianmoronzirfas maybe especially for you?

https://processingfoundation.org/fellowships

We're thrilled to announce an open call for our 2018 Fellowship Program.

Processing Foundation Fellowships support artists, coders, and collectives in visionary projects that conceive a new direction for what Processing as a software and a community can do. Fellowships are an integral part of the Processing Foundation’s work toward developing tools of empowerment and access at the convergence of art and technology. 

We encourage proposals that involve investigations into what a fellow may not already know how to do. This can be initiated at any level of expertise, and we are open to applicants from all backgrounds and skill levels. We place more emphasis on proposals that demonstrate enthusiasm, innovation, and the evolution of a fellow’s practice rather than their pre-existing technical skills. We choose projects that will have a significant impact on the fellow’s practice, and offer them much-needed resources and support. 

Projects can range from software development of the existing Processing projects (Processing, p5.js, Processing.py, Processing for Android), to creative and exploratory research for new iterations, to community outreach initiatives that address barriers to access and diversity. Our past fellowships are good examples of work we believe is important, and of how those projects have evolved into self-sustaining projects in their own right. 

Applicants are encouraged to familiarize themselves with previously supported work, and to envision how their projects might continue beyond the Foundation’s support. (The Processing Foundation Medium account has a series of articles written by the 2017 Fellows in their own words.) 

Fellows will be selected by the Processing Foundation’s Board of Directors. The Board will work with selected fellows to find appropriate mentorship for the project. Fellows are awarded a stipend of $3000 USD, at $30/hour for a total of 100 hours. Fellowship work must take place between March 1 and May 31, 2018, where the 100 hours are distributed according to the fellow’s schedule. 

Regular communication between fellows and their mentor is required, as are regular updates of work in progress, which can take the form of tweets, blog posts, etc. As a culmination of the fellowship, fellows are required to document their project online. 

Application period is open November 15 - December 20, 2017. Selected fellows will be notified by early February 2018. Late applications will not be accepted. 

To apply, go here. If you have questions, please email foundation@processing.org.  

Application Deadline: Wednesday, December 20, 2017,11:59PM PST  

If you are interested in sponsoring a fellow, contact Johanna Hedva, Director of Advocacy: johanna@processing.org! The Foundation is looking for potential funders who would be interested in sponsoring part or all of a fellow’s project. 
Regards, 
Ben, Lauren, Dan, Casey, and Johanna

**Comment by trych** [comment]
I thought about it last year already.
I think the main problem and the criterion for exclusion would be that basil.js is linked to and dependent on Adobe InDesign. Which is one of the least open software packages I can think of... 😞
