### ISSUE TITLE
b.trimWord() could trim a bit more

### ISSUE THREAD

**Issue by trych** [basiljs/basil.js#230]
Hey there,
together with a student we just tried to trim a string `(Foo):` down to `Foo`.
I thought this would be possible using `b.trimWord()` but it did not work and checking the source code now, I saw that trimming `(`, `)` and `:` is not included.

Could we include those as well? As they all could be bordering words, I think it would make sense to include them.

Other candidates: `[]{}"„“«»#@`.

**Comment by fabianmoronzirfas** [comment]
I did not look at the source, but couldn't we use the `words` object? Are special characters there included on the `word`

**Comment by trych** [comment]
Yes, special characters are always part of the word. White space is what separates words. For that reason I would actually include all sorts of special characters that could be at the beginning or end of words in this function.

**Comment by b-g** [comment]
Yes makes totally sense! Please go ahead and trim away anything which is not a “word”.

**Comment by trych** [comment]
Ok, done! #232 
Closing.
