### ISSUE TITLE
Implementing save and restore of user's InDesign settings

### ISSUE THREAD

**Issue by trych** [basiljs/basil.js#239]
(I am referring to #85)

Ok, this turns out to be very tricky.

I have basically implemented the planned behavior now ( [in this branch](https://github.com/basiljs/basil.js/tree/indesignSettings) ) and it works as intended. However, it broke the feature that a basil-script can be undone in one step (as it wants to let you undo all the settings that were set). The "undo in one step" is a feature we should not lose, though.

I am now looking for ways to work around this problem. So a few questions, maybe you guys can help me out:

- Does anyone know if I can somehow include some "pre and post functions" in an `app.doScript()` function?
  So we have this function here:

  ```js
  var runDrawOnce = function() {
    app.doScript(function() {
      if (typeof glob.draw === "function") {
        glob.draw();
      }
    }, ScriptLanguage.javascript, undef, UndoModes.ENTIRE_SCRIPT, pub.SCRIPTNAME);
  };
  ```
  Is there a way to include some pre- and post functions that will be executed before and after the main function (`draw()` ) in this case and can be undone by the user in one step afterwards.

- Would it alternatively be possible to wrap the entire `b.go()` function in an `app.do()` function that would be run in `init()`. That means we have something like:

```js
// all initialisations should go here
var init = function() {
  glob.b = pub;

  welcome();

  // -- init internal state vars --
  startTime = Date.now();
  currStrokeWeight = 1;
  currStrokeTint = 100;
  currFillTint = 100;
  currCanvasMode = pub.PAGE;
  currColorMode = pub.RGB;
  currGradientMode = pub.LINEAR;
  currDocSettings = {};

  app.do(glob.go(), ScriptLanguage.javascript, undef, UndoModes.ENTIRE_SCRIPT, pub.SCRIPTNAME));
};
```

That would also mean we would need to execute scripts _without_ `b.go()`. However, getting rid of `b.go()` [was our plan anyways](https://github.com/basiljs/basil.js/wiki/Basil.js-Team-Call-Summary#bgo-draw-and-setup). @fabianmoronzirfas, I remember you looked into this, do you recall what were the difficulties to implement this? Do you think wrapping `b.go()` into an `app.do()` function withing `init()` would work?

Any help or opinions very appreciated!

**Comment by b-g** [comment]
@trych Tricky :( + I'm afraid, but I don't have more leads. Sorry!

**Comment by trych** [comment]
This has been implemented in the new b-less basil. Closing.
