### ISSUE TITLE
tutorials/basic/05_FunctionPlotter/05_1.jsx –> indesign crash

### ISSUE THREAD

**Issue by b-g** [basiljs/basil.js#24]
kills my indesign cs6 every time ... please check

@ludzeller

**Comment by fabiantheblind** [comment]
I can not confirm. Works for me in:  

- ID CC 2015
- ID CC2014
- ID CS6

**Comment by fabiantheblind** [comment]
Can you please review this if you find the time?

**Comment by b-g** [comment]
Same here, can confirm ID CC 2015 ... I guess it doesn't matter in 2016 if the example might break in cs6. Closed! :)

**Comment by trych** [comment]
I am actually very strongly of the opinion that it does matter a lot in 2016 if it breaks in CS6 or not. CS6 is the last non-subscription version of InDesign, I know *many* students that still run CS6 (including me). And it is the version that you can still install if you have a Adobe CC subscription. Even prominent figures as Jongware still stay with CS6 and refuse to adopt Adobe CC. So, generally I would say, it is very important to stay compatible with CS6, as it is still wide spread today and I assume it will stay for a while.

**Comment by b-g** [comment]
Ok. Then what about contributing a PR? :)

**Comment by trych** [comment]
Will do, when I find the time (and keep learning about Github), but for now I wanted to let you know that there are still quite a few CS6 users out there and we should not simply ignore them. :)

**Comment by fabiantheblind** [comment]
@trych Can you confirm that it works in CS6?

**Comment by trych** [comment]
@fabiantheblind I will, as soon as I get back to my computer with CS6 and basil.js. Traveling right now and writing from my girlfriend's computer. Outrageously, she doesn't have InDesign installed. ;)

**Comment by trych** [comment]
@fabiantheblind Does not crash for me in CS6. Does that mean, we should just keep the issue closed? Or @b-g, do you want to figure out where exactly it crashes?

Apart from that, a side question: Where exactly is the end user going to see these tutorials? As they are not included in the regular download bundle, I was not aware of these tutorials, until they were pointed out in this issue. Did I miss something?
