### ISSUE TITLE
Implementing "b-less"

### ISSUE THREAD

**Issue by trych** [basiljs/basil.js#241]
Hey everybody!

After the [restructuring issues](https://github.com/basiljs/basil.js/issues/239) I had last week @fabianmoronzirfas and me had a quick Skype call on how to implement b-less.

I have given this some thought over the last few days and I think we have come up with a good solution. This issue serves as a roadmap for ourselves and to inform the rest about the plan.

The plan:

- [x] get rid of `b.` (duh!)
- [x] have all the basil functions live in global space
  - [x] get rid of the ~~`pub` and the ~~`glob` object
  - [x] ~~rewrite all functions from `pub.rect = function(args)` to `function rect(args)`~~
  - [x] ~~rewrite all private function calls from `pub.radians()` to `radians(args)`~~
- [x] get rid of `b.go()` and `b.loop()`
- [x] instead the proposal is to have `function setup()` (for inital setup), `function draw()` (to draw your script as we used to have) and `function loop()` (to loop scripts)
  - [x] we decided against swapping `function draw()` for `function setup()`, because in > 99% of all cases, draw will be the only thing that is used in basil, it would be weird to call it setup
- [x] there will be no backwards compatibility: `b.rect()` would not work anymore
- [x] ~~users are responsible themselves not to overwrite the global functions, as this makes the code simpler and cleaner – we think if a user is advanced enough to define his own `rect()` function he should be able to figure out why the basil rect() function stopped working~~ users will get a warning when they define global functions that collide with basil functions
- [x] `b.MODEHIDDEN` etc. can be moved to a dedicated function `mode(HIDDEN)`
- [x] update all documentation to skip the `b.`
- [x] implement a `frameRate()` function to set the frame rate in looping scripts
- [x] implement saving of user defaults and resetting them in the end

That means a typical basil script would look like this in the future:

```js
// @includepath "~/Documents/;%USERPROFILE%Documents";
// @include "basiljs/basil.js";

function draw() {
  rectMode(CENTER);
  rect(50, 50, 200, 80);
  text("Hello basil 2.0!", 100, 100, 60, 60);
}
```

@basiljs Does this sound good for everybody? I would start trying to implement this in the next few days.

**Comment by b-g** [comment]
👍🛠🚀

**Comment by trych** [comment]
Ok, the basic switch went really smoothly and I got basil.js to work without `b.` and without `b.go()`.

I thought a bit more about the issue of users overwriting basil functions and in the meantime I thought we might be in trouble, but now I realize (after writing half the post already) that it's probably fine. I will still finish the post now, so we have it as a future reference, if we ever need to discuss this again. There are three overwriting scenarios to consider.

### 1 – Overwriting public function, then use basil function

```js
function draw() {
  var floor = "lava";
  var randomIndex = floor(random(1, 10));  // --> Reference Error: floor is not a function
}
```

This scenario I find acceptable to have the user figure out himself. I have checked how it works in p5.js, it's exactly the same way. I think if the user defines a basil variable and then later tries to use this variable, he will (via the given error) figure out that his assigning of the variable is the issue.

### 2 – Overwriting private functions/variables

For a second I thought that might get us in trouble and we might need to wrap all the private functions into an object. I thought this code would not work:
```js
function draw() {
  var currDoc = "myDocName.indd";
  addPage();  // no error
```
The private global variable `currDoc` does not get overwritten, because `var currDoc` creates an additional variable `currDoc` in the scope of the `draw` function.

So, an error would only happen, if someone did this:
```js
function draw() {
  currDoc = "myDocName.indd";
  addPage();  // --> Error, addPage() depends on currDoc being a document internally
```
As this is highly unlikely (and really bad practice) I think we can live with this. Also, I think basil 1.0 would have thrown an error as well.

### 3 – Overwriting public function, then use seemingly unrelated basil function

I thought this might be a problem (as `arc` uses `min` internally) and then the user would be super confused why there is an `min` error, when there was no `min` function used:
```js
function draw() {
  var min = "minimini";
  arc(0, 20, 50, 80, 0.3, 0.4);  // no error
}
```

But it turns out that just like in the previous example, it does not cause an error at all. The only way to cause an error is to do:

```js
function draw() {
  min = "minimini";
  arc(0, 20, 50, 80, 0.3, 0.4);  // Reference Error: min is not defined
}
```

Which again, is bad practice anyways and was probably causing issues in basil.js 1.0 as well, so I would leave it at that.

**Comment by trych** [comment]
Maybe I spoke to soon, as I found another overwriting problem and this one bothers me a bit.

```js
function draw() {
  arc(0, 20, 50, 80, 0.3, 0.4); // error
}

function min() {
  return "foo";
}
```

This here throws an error, as the user is overwriting the global function `min` with his custom one. The problem could be avoided if we stick with function expressions instead of functions declarations, i.e. have `var min = function() {}` instead of `function min() {}` as the user function is then overwritten by the basil function. However, this happens without any warning, so the user could get really confused if he did not know that `min` is already  a basil function.

@basiljs Does anybody have an idea how to avoid this problem? @fabianmoronzirfas used an algorithm in his branch, where he manually injected global basil functions into global. Maybe this could be done and then if there is already a global function of said name, an error could be thrown that lets the user know that `min` is a reserved function.

**Comment by fabianmoronzirfas** [comment]
> The problem could be avoided if we stick with function expressions instead of functions declarations, i.e. have var min = function() {} instead of function min() {} as the user function is then overwritten by the basil function. However, this happens without any warning, so the user could get really confused if he did not know that min is already a basil function. 

This should not happen. It would get really confusing.  

>  @fabianmoronzirfas used an algorithm in his branch, where he manually injected ~~global~~ basil functions into global _(scope)_. Maybe this could be done and then if there is already a global function of said name, an error could be thrown that lets the user know that min is a reserved function.  

That is the only way I can think that does not contain having a manually redacted list of function names we are using.

|Pros |Cons|
|:--|:--|
|we stay `b.` compatible|no clean cut. Creates complexity that is not needed|

**Comment by trych** [comment]
> This should not happen. It would get really confusing.
I agree.

So, in this case, I will leave the `pub` object in place and leave the function declarations at `pub.rect = function()` etc. Once all pub.functions are defined, they will be injected into global space. When this happens, there will be checks if it collides with a user defined function, if so, give him an error, similar to the p5 one.

**Comment by trych** [comment]
Also, I find it weird that all private variables and functions are in the global scope. Would it not make sense to move them to their own object, just to be extra sure, they are not being overwritten? Would also organize the code a bit better, because one could see right away, what is a private and what is a public function.

So it would be something like this:

```js

var pub = {};
var prv = {};

...

pub.rect = function() {
...
}

prv.currentLayer = function() {
...
}
```

Or to stay basil-related, maybe `bsl` would make for a nicer prefix:
```js

var pub = {};
var bsl = {};

...

pub.rect = function() {
...
}

bsl.currentLayer = function() {
...
}
```

**Comment by fabianmoronzirfas** [comment]
> So, I guess we should keep the main anonymous function and just do the injection into the global space then, after all basil functions are loaded.  

👍🏽

**Comment by b-g** [comment]
+1

**Comment by ffd8** [comment]
👍

**Comment by fabianmoronzirfas** [comment]
About the split from private and public variables: 
I find `bsl` pretty cryptic. `priv` or `private` and `pub` or `public` are okay IMHO. Having the abbreviation is from a time when there was no autocomplete. It would be better to read if we would use the longer names.

**Comment by b-g** [comment]
But why do we need at all the `private.something`? If we keep the existing structure (with the anonymous function) with the addition of coping everything of `public.something` to the global namespace ... it would simply vote to keep internally `pup` or `puplic` and then bind on the outside all the other stuff under something like `_b.` or `__b.`.

**Comment by trych** [comment]
Yes, no worries. As I stated above that's exactly what I did now. :wink:

**Comment by trych** [comment]
Ok, fyi, kurzer Zwischenstand:

Over the weekend I now implemented the b-less feature in a way that avoids user overwrites by giving them an error, so it should be really user friendly. Also I got rid of `b.go()` and `b.loop()`. The trickiest part was to have global variables of the user script included (if a user wants to use variables for both `setup()` and `loop()`), but I found a way.

I need to clean up the code a bit and then will push a first branch to GitHub. However, before final reviewing there are a few more things that need to be implemented.

Stay tuned. 😃

**Comment by trych** [comment]
I re-implemented now the modes (`MODEHIDDEN`) etc.
It works now with a regular function, that means you can also switch modes in the middle of the script, if you want to hide your script during a certain part.

@basiljs How should the naming of this function be?

I would vote for `mode(CONSTANT)` and then name the constants simply `HIDDEN`, `VISIBLE` and `SILENT` as `mode(MODEHIDDEN)` would sound redundant. So I think `mode(HIDDEN);` would be nice.

Opinions?

**Comment by fabianmoronzirfas** [comment]
++ for `mode(HIDDEN);` and so on

**Comment by b-g** [comment]
+++ for mode(HIDDEN); etc.

**Comment by trych** [comment]
After a lot of frustration today of not getting things to work, I now managed to implement the `frameRate()` function. It can even change the frame rate during script execution 😎.


![framerate](https://user-images.githubusercontent.com/9803905/34747157-4be78f6c-f597-11e7-9596-7b0e4c5366ef.gif)

This is how the script looks:

```js
#targetengine "loop"
// @includepath "~/Documents/;%USERPROFILE%Documents";
// @include "basiljs/basil.js";

var counter = 0;
var tf;

function setup() {
  clear(doc());
  size(200, 200);

  frameRate(3);

  textFont("Arial");
  textSize(48);
  textAlign(Justification.CENTER_ALIGN,  VerticalJustification.CENTER_ALIGN);
  tf = text("Frame rate: " + frameRate(), 0, 0, width, height);

  fill(255, 255, 0);
}

function loop() {

  ellipse(random(width), random(height), 12, 28);
  counter++;

  if(counter === 10) {
    fill(255, 0, 0);
    frameRate(25);
    tf.contents = "Frame rate: " + frameRate();
    arrange(tf, FRONT);
  }

  if(counter === 70) {
    fill(0, 0, 255);
    frameRate(6);
    tf.contents = "Frame rate: " + frameRate();
    arrange(tf, FRONT);
  }

  if(counter === 90) {
    tf.contents = "Done!";
    arrange(tf, FRONT);
    noLoop();
  }

}
```

**Comment by fabianmoronzirfas** [comment]
It looks so processingish without all those `b.`

**Comment by b-g** [comment]
nice! the infinite loop under control! :)

**Comment by fabianmoronzirfas** [comment]
related to #38

**Comment by trych** [comment]
Yes!!! All tests are passing with b-less basil at last!

![bildschirmfoto 2018-01-13 um 17 13 45](https://user-images.githubusercontent.com/9803905/34907850-4ff0fe90-f885-11e7-802a-4eb014a87cd4.png)

Need to do some final cleanup, then will do a PR later today.

**Comment by fabianmoronzirfas** [comment]
![](https://media1.giphy.com/media/aLdiZJmmx4OVW/giphy.gif)

**Comment by trych** [comment]
Hahaha. PR is up now: #243.

**Comment by trych** [comment]
Has been implemented. Closing.
