### ISSUE TITLE
Why cant we use global variables?

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basil.js#244]
Can someone tell me why we can't use global variables?

    ### Basil Warning -> basil could not load global variables.   

[main.js#74](https://github.com/basiljs/basil.js/blob/b-less/src/main.js#L74)

**Comment by fabianmoronzirfas** [comment]
What is the difference between running the script from the scripts panel, Sublime and ESTK?

**Comment by trych** [comment]
Can be closed, as we agreed global variables can be used.
