### ISSUE TITLE
Remove b.storyCount()

### ISSUE THREAD

**Issue by trych** [basiljs/basil.js#247]
Why is there a function `b.storyCount()`? I find it super obscure that we have this. Other functions like `b.wordCount()`, `b.characterCount()` would make much more sense, but we don't even have those.

I would vote to just remove `b.storyCount()` for the basil 2.0 release, as we can just use `b.doc().stories.length`, if we really need to know the story count and I find the function to specific with little gain.

**Comment by b-g** [comment]
Yes, let's get rid of old legacy API stuff, which no longer match our/the new mental map of the 2.0 API.

**Comment by trych** [comment]
Ok, cool. Will maybe go over all functions to check if there are others that could go.

**Comment by trych** [comment]
Removed in #274.
