### ISSUE TITLE
basil.js doesn't work in osx 10.10 (and InDesign CC)

### ISSUE THREAD

**Issue by stephanbogner** [basiljs/basil.js#25]
When I create the alias in "Script Panel"-Folder. Indesign displays it as following.
![screen shot 2014-11-27 at 09 49 25](https://cloud.githubusercontent.com/assets/7897006/5214399/ea54e8d8-761b-11e4-809b-e332feab2b96.png)
Hovering above it reveals: "The file is not executable by any supported script language".
I guess Indesign or the OS (Mac OS Yosemite 10.10 in my case) don't support paths via Aliases properly.

My hackaround was to add the "basil.js"-folder into the "Documents"-folder, as well as into Indesign's scripting folder – However even then not everything was working.

**Comment by ffd8** [comment]
2 year old thread, but incase someone hits this error and finds the conversation... 

Here's a quick fix to the issue. Seems that with CC 10+ aliases broke, however Symbolic Links are still fine to use (and I'm guessing backward compatible for < CS 6).
Just updated our [installation tutorial](http://basiljs.ch/tutorials/installation-and-getting-started/) for the bug. 

Essentially just run the following in Terminal:
`ln -s basiljs_PATH Scripts_Panel_PATH`

Looks like an alias.. acts like an alias.. but InDesign says yes!

**Comment by kjhollen** [comment]
Hey all, I came across this issue trying to troubleshoot on macOS 10.15.7. Wondering if anyone's seen this lately? I created the sym link via command line, but it's not showing in the Scripts panel in InDesign (v16.0, if that helps).

**Comment by trych** [comment]
Hi @kjhollen , I believe it should still work, I just tested it with the most recent InDesign version and the most recent macOS, I believe all previous versions should have worked as well. Are you sure you had the paths in your terminal command correct? It should be something like:

`ln -s /Users/your_user_name/Documents/basiljs /Users/your_user_name/Library/Preferences/Adobe\ InDesign/Version\ 17.0/de_DE/Scripts/Scripts\ Panel`

**Comment by kjhollen** [comment]
hi @trych, yes I could see the link in the correct place in Finder but InDesign wouldn't register it. When I copied an actual file into the directory instead, the Scripts panel would show it, but it would never show the symlinked files.

I worked around this by using the Sublime Text workflow you described here: https://github.com/trych/MuTypo (in case it's useful to anyone else facing this issue!)
