### ISSUE TITLE
basil.js image api doesn't allow importing of vector files

### ISSUE THREAD

**Issue by iros** [basiljs/basil.js#26]
It would be really great to be able to import and place images that are vectorized, such as SVG (or .ai files directly) with the image API. Is that possible? I haven't been able to do so and can't quite parse the InDesign docs for instructions on doing so.

Thanks!

**Comment by fabiantheblind** [comment]
Hi @iros 

Sorry for the long delay on your issue. It is actually possible to place Illustrator files. The code below should show you how.  



    #includepath "~/Documents/;%USERPROFILE%Documents";
    #include "basiljs/bundle/basil.js";
    function draw() {
      // b.image("test.ai",0); // does not work as expected
      b.image("test.ai", 0, 0, 100, 100); // works as expected
      var rect = b.rect(0, 100, 100, 100); // create a rectangle to place the image in
      b.image("test.ai", rect); // works as expected
    }
    b.go();

There is a bug with the method when using just `b.image("filename.ai", x);` We will take a look into this.  

Attached is a .zip file with a test setup.

[basil-place-ai-file.zip](https://github.com/basiljs/basil.js/files/349587/basil-place-ai-file.zip)
