### ISSUE TITLE
Markdown in jsDoc comments

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basil.js#267]
Is it possible to use [M]↓ in jsDoc comments even though we are using documentation.js for creating the data?

**Comment by trych** [comment]
Ok, Markdown does not seem to work by default. If I have a description text containing back ticks for example it works like this:

Original
```
* I am describing something, showing some `inline code`.
```

Turns into
```
description: 'I am describing something, showing some'
```
in the yaml front matter.

If I use a description tag, it will not cut it off, but just literally render the backticks:

Original
```
* @description I am describing something, showing some `inline code`.
```

Turns into
```
description: 'I am describing something, showing some `inline code`.'
```
in the yaml front matter.

I wonder if Jekylls markdownify could be used to render this markdown (that is found in the yaml front matter), as it is described [here](https://stackoverflow.com/a/21820968/3399765). @fabianmoronzirfas  Could you tell me, where the description's parsing from yaml to Jekyll is actually happening, i.e. where I could add this `markdownify` keyword as shown in the linked post? Then I could test, if this works, and if so, we would have easy markdown without switching to jsdocs.

**Comment by fabianmoronzirfas** [comment]
You can’t add it. I’ll have to do that.

**Comment by fabianmoronzirfas** [comment]
Can we take this over as an issue to the site?

**Comment by fabianmoronzirfas** [comment]
This is already done. https://basiljs2.netlify.com/reference/math/norm.html vs https://github.com/basiljs/basil.js/blob/develop/src/includes/math.js#L213 Closing
