### ISSUE TITLE
What is this Random (gaussian distribution) method?

### ISSUE THREAD

**Issue by trych** [basiljs/basil.js#272]
There is this method named `Random` (as opposed to the method `random` that we all know and use), which can be found [here in math.js](https://github.com/basiljs/basil.js/blob/c016ce3e5c81b042b94caff1d5d8d3cd4250ca05/src/includes/math.js#L749).

What does this method do? It does not seem to return anything and it also does not seem to be a private method that is used in another function?

Can I assume we can remove this?

**Comment by b-g** [comment]
Danke für die Adleraugen!!

Back then I’ve ported basically everything what was possible from processing.js to basil. The idea was to review later whether it is useful or not. As apparently nobody every used it … we should remove it (or rename to the p5,js equivalent, there should be be one)

What is doing:
> Random Generator with Gaussian distribution.

`pub.Random(123).nextGaussian()` should give you nicely random numbers in a Gaussian distribution (based on seed 124).

**Comment by trych** [comment]
Ok, in p5.js it is a [standalone method](https://p5js.org/reference/#/p5/randomGaussian) `randomGaussian()` that also does not have a seed argument, but rather has takes the mean and the standard deviation as optional arguments.

I would vote to take the current `Random` out, as it is not documented well, does not really fit the general basil.js style and does not match the p5 method in syntax.

**Comment by b-g** [comment]
Ok. +1 for removing it.

**Comment by trych** [comment]
Removed in #273. Closing.
