### ISSUE TITLE
MAX_FLOAT etc

### ISSUE THREAD

**Issue by clankill3r** [basiljs/basil.js#28]
It would be nice to have b.MAX_FLOAT, b.MIN_FLOAT etc. to be a bit more equal to processing.

**Comment by trych** [comment]
What are `MAX_FLOAT` and `MIN_FLOAT` supposed to do? On the processing reference I can only find `min` and `max`, which seems to work just like `b.min()` and `b.max()`.

**Comment by clankill3r** [comment]
MAX_FLOAT is the highest value possible just like MAX_INT. 

MAX_INT for example is 2147483647.

**Comment by trych** [comment]
Ah, now I see. Seems to be different in JavaScript though ([see here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_VALUE)):

```
Number.MAX_VALUE: 1.7976931348623157e+308
Number.MIN_VALUE: 2.2250738585072e-308
```
```
Number.MAX_SAFE_INTEGER: 9007199254740991  // ES6 only
Number.MIN_SAFE_INTEGER: -9007199254740991 // ES6 only
```
```
Number.POSITIVE_INFINITY: Infinity
Number.NEGATIVE_INFINITY: -Infinity
```

Could you explain what a use case for these could be in a basil.js context? I don't think anybody wants to run a for lopp up to b.MAX_SAFE_INTEGER?

**Comment by trych** [comment]
Closing this, as I see no real use case and `Number.MAX_VALUE` can be easily used as the equivalent to Processing's `Float.MAX_VALUE`.
