### ISSUE TITLE
Bundle vs release

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basil.js#302]
I just noted that the basil.js bundle does not have a timestamp. @trych  are you only running `npm run bundle` when you add features? If so - how should we handle this? 

Should we: 

- add the timestamp to the bundle npm script
- or force everyone to run the release script when there is a new feature?

**Comment by trych** [comment]
No, we discussed this once that we don't have a time stamp and a version in the develop branch, but only when we push it to master we will add this information. And yes, I use npm run bundle when adding stuff to basil.js.

**Comment by fabianmoronzirfas** [comment]
Okay. When we already discussed that we can close this one. Did we agree but to follow semver?

**Comment by trych** [comment]
Yes, we had the semver discussion as well and agreed (tldr version) to always collect the amount of new features that we think feels right and then decide on a release. Then, when we release it, we look at the features and see, if they involve any to cause either a 0.0.x bump only, a 0.x.0 bump or even a x.0.0 bump.
