### ISSUE TITLE
How can I execute a basiljs script directly from terminal?

### ISSUE THREAD

**Issue by gsomeone** [basiljs/basil.js#304]
I'm trying to create a `jsx` file that gets executed when something else happens in another program. I am confident I can do that if I find the way to launch the jsx file from the terminal. 

Has anybody already did this? Is there any documentation? 

Background:
I am creating a tool to show shapes to a webcam to rapidly prototype designs in a tangible way.

**Comment by fabianmoronzirfas** [comment]
Take a look at this stackoverflow answer https://stackoverflow.com/a/37323769/1770432 
You might need to bundle all the scripts.

**Comment by fabianmoronzirfas** [comment]
There is currently a bug related to ESTK which might make this harder https://medium.com/adobetech/extendscript-toolkit-debugger-error-1116-67cce4d47af7

**Comment by ffd8** [comment]
A student had success by first having the script accessible within the scripts user panel – then you can make custom shortcuts to launch a script. From there – you can use applescript or we used Processing + robot library to control the computer and press that command key.

**Comment by fabianmoronzirfas** [comment]
Should still be possible but I don't have any examples floating around
