### ISSUE TITLE
transform position throwing an error

### ISSUE THREAD

**Issue by ffd8** [basiljs/basil.js#308]
Just ran into this today:

```
var sel = selection();
transform(sel, "position", [50, 50]);
```

throws an 'TypeError: undefined is not an object'

**Comment by trych** [comment]
Yes, I ran into this the other day, too. This seems to be related to the `isArray()` change I did recently. Damn. Unfortunately I will have no time to look into this in the next few days. Is it an option to use

```js
var sel = selection();
transform(sel, "x", 50);
transform(sel, "y", 50);
```
instead?

**Comment by trych** [comment]
Ok, my suggestion does not work. Damn, this really breaks the `transform()` function. I will see if I can do a quick fix, because I need this to work for my course as well. 😆

**Comment by ffd8** [comment]
Haha no rush, just happy to learn it's not unique to our setup. Great when you have a chance to check it out.
