### ISSUE TITLE
Type on path hard to access...

### ISSUE THREAD

**Issue by ffd8** [basiljs/basil.js#309]
Did a demo today of putting text on a path = great new feature! 
Only tricky thing is then talking to it with our typo function:

```
var myLine = line(0, height, width, 0); // make line
var tf = text(LOREM, myLine); // put text on line
//typo(tf, "pointSize", 50); // doesn't work (but should?)
//typo(myLine, "pointSize", 50); // wrong, shouldn't be used
//inspect(tf); // helped me find tf.texts[0]
typo(tf.texts[0], "pointSize", 50); // works, but not friendly at all
```

No problems when placing text into a shape/polygon, so it's an issue with text on a path.
Perhaps `typo()` just needs to check if it's a typoonpath then somehow return that `texts[0]` object?

**Comment by trych** [comment]
Fixed in #311.
