### ISSUE TITLE
Remove global constants from listing

### ISSUE THREAD

**Issue by ff6347** [basiljs/basil.js#317]
Currently all the global constants are not marked as the `@subcat constants`. That is why they get the `()` at the end in the reference.  Would be good if we would mark them as such https://github.com/basiljs/basil.js/blob/develop/src/includes/constants.js

**Comment by fabianmoronzirfas** [comment]
Q: Should we add the `@cat global` to the constants? Would not make a difference for the docs but would clearer…

**Comment by fabianmoronzirfas** [comment]
Ah okay. Direkt remember this. I guess the easiest way is them to remove the blockcomment and use regular comments on the ones that should be excluded

**Comment by fabianmoronzirfas** [comment]
I removed the block comments with the latest push on the PR. #318
