### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by trych** [basiljs/basil.js#325]
I think there are some files that we don't need anymore. Before I remove them from the `develop`-branch, I want to make sure they can go. Please check each that can go.

- [x] `extras` (holds Sublime Text build scripts. I think we don't need them anymore as the external `Run in InDesign`-Sublime package offers much better functionality).
- [x] `yuidoc.json` (we don't use yuidoc anymore)
- [x] `roadmap.md` (is outdated and can rather be managed over GitHub functionality)
- [x] `install.bat` & `install.command` (not sure about those, do we need them? @fabianmoronzirfas )
- [x] `basil.sublime-project` (not sure about this one either? Do I need it, if I develop in Sublime? If so, it could probably be added to `.gitignore`, so it stays for those who need it).

**Comment by fabianmoronzirfas** [comment]
IMO install.bat and install.command can be removed. They are a thing of v1 installing the whole folder with all the deps.

**Comment by trych** [comment]
Done.
