### ISSUE TITLE
ES6 support?

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basil.js#40]
Rewrite Basil to be real ES6 modules. Can be done using [ExtendScript/extendscriptr](https://github.com/ExtendScript/extendscriptr). The user would still write plain old ExtendScript but Basil itself would be easier to handle

**Comment by fabiantheblind** [comment]
See also #39

**Comment by fabianmoronzirfas** [comment]
I think this should not be done. Teaching ES6 in Extendscript would mean to teach the whole build process. It makes no sense. We would decouple the students from the actual ES3 environment Extendscript is.
