### ISSUE TITLE
Use everyItem or itemByRange instead of loops for better performance in core

### ISSUE THREAD

**Issue by fabiantheblind** [basiljs/basil.js#51]
As mentioned in issue #44

**Comment by fabiantheblind** [comment]
I've been snooping around the source. Actually there are not a lot of for loops used to get elements. 👍  There are some forEach loops though. these can't be replaced by a everyitem() call. The everyItem or itemByRange can be used to set properties but there is no way to run a function on each item.

**Comment by b-g** [comment]
Many thanks for double checking this nitty gritty performance detail!! I guess we can close the issue then?

**Comment by fabiantheblind** [comment]
Yes we can.
