### ISSUE TITLE
rework b.width for getting the width of several spreads

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basil.js#54]
as mentioned in #50

**Comment by trych** [comment]
Ok, I did not realize that `b.width` always refers to the _canvas_ width and that it is closely related to the whole canvas mode business. I always assumed, it simply returns the width of the current page (as is stated in the reference).

I would suggest the following improvements:

1. Make `b.width` refer to the canvas width specifically and correct the description in the reference.
2. Make `b.width` work for spreads with more than 2 pages. This probably includes changing the canvas modes `b.FACING_PAGES`, `b.FACING_MARGINS` and `b.FACING_BLEEDS` to `b.SPREAD`, `b.SPREAD_MARGINS` and `b.SPREAD_BLEEDS` (or is it important that they are called Facing pages?). For backwards compatibility we could either keep b.FACING_PAGES & Co. to still work, or we keep the old names and just change how the methods work internally.
3. Introduce a new method `b.pageWidth` that returns the page width, independently from the current canvas.
4. Introduce a new method `b.spreadWidth` that returns the spread, no matter how many pages, independently from the current canvas.

**Comment by trych** [comment]
This can be closed, as `width` now returns the correct value referring to the currently set canvas mode. My suggestions about `pageWidth` and `spreadWidth` from above could rather be solved via `bounds()` (see #276).
