### ISSUE TITLE
Trailing white space

### ISSUE THREAD

**Issue by trych** [basiljs/basil.js#63]
One of the issues with a closed PR of mine was that Sublime automatically trims trailing white space at saving time for me. So I had a whole lot deletions, without realizing why, although I only actively changed a few lines.
To prevent issues like these in the future, would it be okay, if I created a PR, removing all unnecessary white spaces at the lines' ends? Would only take two minutes or so for somebody to double check, but prevents confusions like these in the future and keeps the files clean.

**Comment by fabiantheblind** [comment]
This should go hand in hand with #34 and #36 I would love to see some kind of linter (eslint?) and maybe a editorconfig

**Comment by trych** [comment]
Ok, then I rather wait for your proper linting and set `"trim_trailing_white_space_on_save": false` for the time being. But I think if we all start to work on basil.js in the coming weeks this would be nice to have at an early point.

Issue can be closed.

**Comment by fabiantheblind** [comment]
Okidoki. I will create a .eslintrc ASAP with settings that match https://github.com/basiljs/basil.js/wiki#coding-conventions-and-rules

**Comment by b-g** [comment]
Hi guys, totally agree an .editorconfig e.g. https://github.com/generative-design/Code-Package-p5.js/blob/master/.editorconfig would be great (compatible w/ agreed code conventions). We tried back then to "solve" this with a sublime text project file https://github.com/basiljs/basil.js/blob/master/basil.sublime-project ... which never really worked out (we should get rid of the file). Best, Bene
