### ISSUE TITLE
b.objectStyle(), b.characterStyle() and b.paragraphStyle() don't work

### ISSUE THREAD

**Issue by trych** [basiljs/basil.js#64]
As the title states, neither of these methods work at the moment, as they make an incorrect call to `findInCollectionByName()` by only providing a `name` parameter instead of both a `collection` and `name` parameter. At the moment the methods conveniently return the first letter of the paragraphStyle name you provide. ;)

I suggest getting rid of the `findCollectionByName()` helper function altogether and replace it by `collection.itemByName("name").isValid` throughout basil.js.

**Comment by trych** [comment]
And we have to think about how to handle `paragraphStyleGroups`.
I would suggest that when adding a new `paragraphStyle` with the method we should only allow them to be added to the top level.

For getting a `paragraphStyle` with the method, we could either

1.) Decide to only search on top level (assuming that in basil.js scripts hardly ever a `paragraphStyleGroup` will be used)
2.) or we can search through all `paragraphStyleGroups` and return the first style with the name that is found, similar to how `b.nameOnPage()` returns the first page item of the name that it finds. This _would_ require a helper function, as the property `doc.allParagraphStyles` that we need provides an array, not a collection, so we could not `itemByName`.

Opinions?

**Comment by fabiantheblind** [comment]
@trych I'm until beginning of August to busy to review this. Basically we can't ignore those damn groups so we need to fix this. If the helper is not working we should fall back to IDAPI calls.

**Comment by fabiantheblind** [comment]
So option 2 it is.

**Comment by trych** [comment]
@fabiantheblind No worries! No need to respond to everything immediately, it is just that I finally found some time _right now_, so I want to hunt for bugs and bring the project forward, so atm I just post issues when I find some. Of course they can all be reviewed when you or somebody else finds the time. Github issues don't expire. ;)

And yes, I agree it should be option 2, so we get rid of one helper function and add another small helper function to handle the styleGroups where necessary.

Small side question:
Which notation do you prefer for me to replace
```JavaScript
newCol = findInCollectionByName(currentDoc().swatches, a);
```
(that expect either a `[swatch]` or `null` in return)?

A)
```JavaScript
newCol = currentDoc().swatches.itemByName(a) || null;
```
B)
```JavaScript
newCol = currentDoc().swatches.itemByName(a).isValid ? currentDoc().swatches.itemByName(a) : null;
```
C)
```JavaScript
if (currentDoc().swatches.itemByName(a).isValid) {
  newCol = currentDoc().swatches.itemByName(a);
} else {
  newCol = null;
}
```

I prefer notation type **A)**, it's the one that Douglas Crockford suggests for falling back on default values after receiving a `false` value and it's nice and short. However, not everybody likes (or maybe knows) it, so I wanted to ask, if it is okay to use.

**Comment by trych** [comment]
Ok, just to let you guys know, I'm working on this. However, in the current master (so before my fixes) I found some minor errors with `b.color()` and one critical one (will create an issue later) and I don't get to work `b.addToStory()` at all at the moment (also in master, just reported that in issue #44 ). So I will investigate these errors first, before I do a PR.

**Comment by fabiantheblind** [comment]
see #66, #67, #68

**Comment by fabianmoronzirfas** [comment]
@trych whats the status of this issue?

**Comment by trych** [comment]
Just closed them.
