### ISSUE TITLE
making trych a member of Basil Org?

### ISSUE THREAD

**Issue by fabiantheblind** [basiljs/basil.js#70]
Clearly @trych is putting some effort into tracking bugs and fixing them. :+1: I propose making him a member so he can add labels, add issues to milestones and so on.

**Comment by b-g** [comment]
Done! Sorry that this took us a while (we all were ooo) ... but I'm now part of the Owner group of the basiljs organisation. Yay! Please approach me for any admin repo stuff. 

@trych, Once more a warm welcome!

**Comment by trych** [comment]
@b-g Thanks! Looking forward to bringing the project forward!
