### ISSUE TITLE
Allow b.clear() to clear specific collections

### ISSUE THREAD

**Issue by trych** [basiljs/basil.js#78]
This is something that has annoying me for a while.

When I use `b.clear(b.doc())` at the beginning of a script that I am working on, to always clear the doc in the beginning, it does naturally not clear things like `layers` etc. This can become really annoying when I am building a script that adds layers. I either have to always manually delete them, manually undo or write some non-basil code to delete layers.

It would therefore be nice, if I could clear specific collections in a container.

So `b.clear(b.doc())` could just work as before, to clear `allPageItems` from that container, whereas I could use `b.clear(b.doc(), "layers")` to clear all layers of doc. Or `b.clear(b.doc(), "colors")` or `b.clear(b.doc(), "allParagraphStyles")` etc. It could also be used, if you only want to clear specific `pageItems`, i.e. `b.clear(b.doc(), "rectangles")`.

What are your thoughts on this?

If we implement this, we would need to add some exception handling, too, because with some collections there are default instances that can't be deleted (layers, swatches etc.).

Please flag as feature and enhancement.

**Comment by ffd8** [comment]
Tricky area.. if you clear the layers - then you'd have to immediately rebuild one or else problems probably occur.. and removing colors = removing all defaults on the person? Of course ideal to only remove anything beyond the defaults. I'd recommend sticking to just the single parameter input and perhaps adding additional input possibilities, ie b.clear(b.colors()),  b.clear(b.layers()) b.clear(b.paragraphStyles()) – or as you suggest using "colors" string options. But again, running into the defaults issue... also with paragraphStyles.. all of those things have a few that are also likely unique per language installation- so could really mess people up if removing and rebuilding things in English? 

From my experience, when generating tons of random colors for example.. perhaps it's best people try something and if they don't like it, undo'ing allows everything that was just rendered to be removed. Another option would be to see if InDesign has a special collection for EVERYTHING new that has been added to the document and that simply needs to be added to the b.doc() grabber?

**Comment by trych** [comment]
@ffd8 Thanks for looking into this!

Well, the undoing step is what I am trying to avoid. ;)

InDesign simply does not allow the deletion or alteration of default swatches and styles. So with a try catch statement we could simply start removing everything from the back of the collection until we hit the first one that we can't remove. That will always leave us with the first four swatches or the first paragraphStyles etc. The layer collection has the exception that you can rename the first layer. But you still can't remove it (i.e. there _always_ needs to be at least one layer). That means we do _not_ have to rebuild anything (which would indeed be messy), the defaults will just stay in place.

So the worst that could happen is that a user renames the layer in the script and then is left with a layer of a different name as his only layer. If that bothers him, he could just alter the script. But we would actually not be messing with any defaults, neither with the defaults of the document, nor with the defaults of the InDesign installation.

I picked the `b.clear(container, "collection")` notation because it is compatible with the way the method works now and because it is equal to the notation of `b.typo(item, "property")`, so I thought this is the basil.js way of doing it. And I think it is actually quite useful to not have a single parameter input, because then you could more precisely determine which collection should be deleted in which container, i.e.:

`b.clear(b.doc(), "rectangles")`

vs.

`b.clear(b.page(), "rectangles")`

I think it would make the method quite a bit more flexible and useful (and offer a great helper while you are still in the process of writing a script) and I don't think it messes up anything for anybody (correct me, if I'm wrong!).

**Comment by fabiantheblind** [comment]
Sounds like a good idea. How would you handle a case where the user wants to clear layers and paragraphStyles and leave colors as is?

    b.clear(b.doc(), [layers, paragraphStyles])

Another idea: couldn't `b.clear()` without parameters just create a new document?

**Comment by trych** [comment]
> Sounds like a good idea. How would you handle a case where the user wants to clear layers and paragraphStyles and leave colors as is?

You always have to address the specific collection you want to clear. That means `b.clear(b.doc())` would _not_ clear `layers`, `colors`, `paragraphStyles`, etc. but just clear `pageItems` as it did until now (also for backwards compatibility). To clear layers and paragraphStyles, you simply do

```JavaScript
b.clear(b.doc(), "layers");
b.clear(b.doc(), "paragraphStyles");
```
I am not sure, do you think it would be better to also allow property arrays? Or does it rather over-complicate things?

> Another idea: couldn't b.clear() without parameters just create a new document?

You mean the same as `b.doc()`? The thing is that if you run this repeatedly, you end up with a whole lot of open documents. How about `b.clear()` without parameters is a combination of `b.close(false)` and `b.doc()`? So it would first close the current document without saving (we could make sure that it is a document that was never saved to avoid closing other projects that were open) and then just open a new clean one.

That means if you are working on scripts, instead of putting `b.clear(b.doc())`at the beginning (and then still having issues with layers piling up), you could just put `b.clear()` and then always have the script perform on a truly new and clean document. I think that would be cool!

**Comment by trych** [comment]
@fabianmoronzirfas What do you think, with the proposal of `b.revert()` ( #133), do we still need this at all? It might be useful, but I think as we would have a good alternative now, it is not such an important feature to add and it might make `b.clear()` unnecessarily complicated.

If you agree, let's close this issue.

**Comment by fabianmoronzirfas** [comment]
Yes. Revert is better
