### ISSUE TITLE
Use a more sophisticated branching model

### ISSUE THREAD

**Issue by trych** [basiljs/basil.js#89]
As there is now some talk about bundling basil.js and related to that the discussion, [if it should rebundled with every PR](https://github.com/basiljs/basil.js/pull/87#issuecomment-244788012), I would like to suggest to move to a more sophisticated branching model, which helps keeping branches clean and has branches for specific purposes (develop, release, master, hotfix etc.)

The branching model explained in the article [»A successful Git branching model«](http://nvie.com/posts/a-successful-git-branching-model/) seems to be pretty popular and wide spread and it seems pretty clean and tidy to me. If you guys have not come across it yet, could you give it a quick read and let us know, if this is a branching model, that we should use as well?

As for the rebundle-on-every-PR-question, in this branching model it would make sense to only rebundle once a release branch is initialized, which to me seems to make more sense than to rebundle on every minor change (that is not going to be released by itself anyways).

What do you guys think?

**Comment by fabianmoronzirfas** [comment]
So as I understand it.  

- `develop` is the development base were all `feature-*` branches get branched from and merged into.
- `release-*.*.*` is the actuall release and gets created from `develop`
- `master` has always the latest `release-*.*.*` state
- `hotfix-*` gets branched from and merged into `develop`
- always merge with `--no-ff`
- always bump a patch version when creating a `hotfix-*.*.*` branch

Did I miss something?

**Comment by b-g** [comment]
OK for me, if I don't have to be dealing and feel responsible for all of this. I'm happy to push my commits to `develop` ... but I'm not so keen to take care of all the rest! :) Hence are there any git house keeper volunteers?

**Comment by fabianmoronzirfas** [comment]
I can do the housekeeping. Even though I also think this system for large teams. _A bit of overhead for just 3-4 contributors._ 

- Would be good to know what is needed for the "release" to the site. Just backing a zip with the master as a folder called bundle and removing the .git folder and any additional dot files?  
- Should we remove the src from the download for the site?

**Comment by b-g** [comment]
Same feelings here. Maybe `master` and `develop` is for the start enough?

For the release package see http://basiljs.ch/wp-content/uploads/2012/11/basil.js-1.0.10.zip would be cool to have for this a grunt/gulp process :)

Yes.

**Comment by fabianmoronzirfas** [comment]
> would be cool to have for this a grunt/gulp process :)
I'm trying to avoid grunt/gulp as long as possible. But yes I want a automated process for this as well.  

> Same feelings here. Maybe `master` and `develop` is for the start enough?  

I would say so. New features still should be in their own branch. So the process would be:  

                                +-------------+
                                |  feature 1  |
                                +-------------+
                                  |
                                  | merge into
                                  v
    +-----------+  merge into   +----------------------------+  merge into   +-----------+
    | feature 2 | ------------> |                            | <------------ | feature 4 |
    +-----------+               |          develop           |               +-----------+
    +-----------+  merge into   |                            |  merge into   +-----------+
    | feature 3 | ------------> |                            | <------------ | feature 5 |
    +-----------+               +----------------------------+               +-----------+
                                  |              ^
                                  | merge into   | merge into
                                  v              |
                                +-------------++-------------+
                                |   master    ||  feature 6  |
                                +-------------++-------------+
                                  |
                                  | pack for
                                  v
                                +-------------+
                                |   release   |
                                +-------------+

**Comment by trych** [comment]
> Maybe master and develop is for the start enough?

Sounds good to me. So the master branch would only ever reflect the state of the latest release then.

**Comment by trych** [comment]
This probably means we should create a develop branch from the current master and then reset the current master to the state of the last release, right?

**Comment by b-g** [comment]
Yes, if we outlay it strict ... or we could also do a maintenance release to get something out of this. Up to you guys.

**Comment by fabianmoronzirfas** [comment]
Lets go for 1.0.11 and then start with the dev branch. No resetting please. There is no code god that will punish us if we use branches how we like.
