### ISSUE TITLE
basil conflicts with active paragraphStyle/characterStyle

### ISSUE THREAD

**Issue by trych** [basiljs/basil.js#96]
If there is a (non-default) characterStyle or paragraphStyle currently selected in the according panels, then the styles of newly created texts get messed up.

Example:
A character style `red` (with a simple red fill color) is selected in the Character Styles panel, then a basil script is run, utilizing `b.text()` at some point. As a selected style always means that the style is applied to newly created text, the character style will be applied to the new text. At the same time however, basil's initial setup sets the text's fill color to black.

The result: The entire text has the character style `red` applied, but in a modified (black) state, so the character style panel shows `red+`.

Same goes for paragraph style.

As this is really messy and surely not the expected behavior when a basil script is run, I suggest to save the currently active character and paragraph style at the beginning of the basil procedure, then set the active styles to the default `[None]` styles, let the script run and reset it to the previously active styles in the end. Similar to what is suggested in #85, except we switch the active styles to the defaults temporarily.

What do you think?

**Comment by b-g** [comment]
Hi @trych, Thanks for the investigation! I was not aware of this. The way outlined the solution, works for me and makes totally sense. I guess, simply go ahead ... @fabianmoronzirfas @ffd8 plz quickly veto if you see it different.

**Comment by fabianmoronzirfas** [comment]
No veto from my side. We should compile a list of things to be saved and restored on script run. Can you guys edit the issue #85 ? If so we just could use the list there.

**Comment by b-g** [comment]
@fabianmoronzirfas Yes And yes let's use #85 to keep track of "restore" things ... and as we have a decision I will close this issue
